# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Outgoing-message publisher for the dynamic-configuration flow.

Two messages originate on the py-analytics side:

* ``request-config`` (Flow B bootstrap) -- emitted once per process at startup
  to ask the video analytics api for the latest verified config from the DB.
* ``ack`` (Flow A reply) -- emitted after every ``upsert`` apply attempt to
  tell the video analytics api what happened (success / partial-success / failure).

Both land on the ``mdx-notification`` topic with the constant message key
``behavior-analytics-config`` so calibration messages on the same topic are
not affected, plus the envelope headers ``event.type`` and ``reference-id``.
"""

import json
import logging
from collections.abc import Mapping
from typing import Any

from mdx.analytics.core.stream.sink.sink_base import Sink
from mdx.analytics.core.transform.config.config_applier import ApplyResult

logger = logging.getLogger(__name__)


# Constants matching the design spec; consumers on the calibration listener
# filter by ``key`` so this value must not collide with calibration's key.
NOTIFICATION_DEST_KEY: str = "notification"
NOTIFICATION_MESSAGE_KEY: str = "behavior-analytics-config"
EVENT_TYPE_REQUEST_CONFIG: str = "request-config"
EVENT_TYPE_ACK: str = "ack"


# Payload shape factory that mirrors the spec table:
#   value: { status, config, error }
def _build_payload(
    status: str | None,
    config: dict[str, Any] | None,
    error: str | None,
) -> dict[str, Any]:
    """Construct the JSON-serializable message body for both event types."""
    return {
        "status": status,
        "config": config,
        "error": error,
    }


class ConfigPublisher:
    """
    Publish ``request-config`` and ``ack`` messages on ``mdx-notification``.

    The publisher is intentionally stateless beyond its sink reference -- the
    listener owns the ``reference-id`` lifecycle (it knows which incoming ref
    to echo back on ack, and the bootstrap ref it generated on Flow B) and
    hands that value in on every publish call.

    :ivar Sink _sink: The shared application sink used by the parent
        :class:`BaseApp` for all outgoing traffic.
    """

    def __init__(self, sink: Sink) -> None:
        """
        Initialize the publisher.

        :param Sink sink: A configured sink for the active streaming backend
            (Kafka / Redis Streams / MQTT). Must have ``notification``
            registered as a destination key in the underlying config.
        :return: None
        """
        self._sink = sink


    def publish_request_config(self, reference_id: str) -> None:
        """
        Emit a ``request-config`` (Flow B bootstrap).

        Sent once per process at startup. The matching ``upsert-all`` reply
        from the video analytics api will carry the same ``reference-id`` -- the listener uses
        it to filter so each replica only adopts its own bootstrap reply.

        :param str reference_id: Identifier of the form
            ``"behavior-analytics-<uuid>"`` generated by the caller (typically
            the listener) and stable for this process's lifetime.
        :return: None
        """
        payload = _build_payload(status=None, config=None, error=None)
        self._publish(EVENT_TYPE_REQUEST_CONFIG, reference_id, payload)


    def publish_ack(self, reference_id: str, result: ApplyResult) -> None:
        """
        Emit an ``ack`` (Flow A reply) carrying the outcome of an upsert.

        The ``reference-id`` echoes the one from the incoming ``upsert`` so
        the video analytics api can correlate this reply with the request it just published.

        :param str reference_id: Echoed from the inbound ``upsert`` message.
        :param ApplyResult result: Outcome from
            :meth:`ConfigApplier.apply_upsert`. ``status`` /
            ``error`` / ``config`` are forwarded verbatim into the
            payload.
        :return: None
        """
        payload = _build_payload(
            status=result.status,
            config=result.config,
            error=result.error,
        )
        self._publish(EVENT_TYPE_ACK, reference_id, payload)


    def _publish(
        self,
        event_type: str,
        reference_id: str,
        payload: dict[str, Any],
    ) -> None:
        """
        Serialize the payload to JSON bytes and send it through the sink.

        Wrapped in try/except: a failed publish must not crash the listener
        thread or the apply pipeline. Persistent backend issues are visible
        via the error log.

        :param str event_type: Goes into the ``event.type`` header.
        :param str reference_id: Goes into the ``reference-id`` header.
        :param dict payload: JSON-serializable message body.
        :return: None
        """
        headers: Mapping[str, bytes] = {
            "event.type": event_type.encode("utf-8"),
            "reference-id": reference_id.encode("utf-8"),
        }
        try:
            message_bytes = json.dumps(payload).encode("utf-8")
            self._sink.write_msg(
                dest_key=NOTIFICATION_DEST_KEY,
                message=message_bytes,
                key=NOTIFICATION_MESSAGE_KEY.encode("utf-8"),
                headers=headers,
            )
            logger.debug(
                f"published {event_type} reference-id={reference_id} bytes={len(message_bytes)}"
            )
        except Exception as e:
            logger.exception(
                f"failed to publish {event_type} for reference-id={reference_id}: {e}"
            )
