"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ImageFormat:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ImageFormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ImageFormat.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RAW: _ImageFormat.ValueType  # 0
    JPG: _ImageFormat.ValueType  # 1
    JPEG: _ImageFormat.ValueType  # 2
    PNG: _ImageFormat.ValueType  # 3

class ImageFormat(_ImageFormat, metaclass=_ImageFormatEnumTypeWrapper): ...

RAW: ImageFormat.ValueType  # 0
JPG: ImageFormat.ValueType  # 1
JPEG: ImageFormat.ValueType  # 2
PNG: ImageFormat.ValueType  # 3
global___ImageFormat = ImageFormat

@typing.final
class Frame(google.protobuf.message.Message):
    """
    represent metadata in a video frame
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    VERSION_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    SENSORID_FIELD_NUMBER: builtins.int
    OBJECTS_FIELD_NUMBER: builtins.int
    FOV_FIELD_NUMBER: builtins.int
    ROIS_FIELD_NUMBER: builtins.int
    SOCIALDISTANCING_FIELD_NUMBER: builtins.int
    SEGMENTATION_FIELD_NUMBER: builtins.int
    INTERACTIONS_FIELD_NUMBER: builtins.int
    CONGESTIONS_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    version: builtins.str
    """
    version
    """
    id: builtins.str
    """
    frame id
    """
    sensorId: builtins.str
    """
    sensor id
    """
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """
        timestamp in UTC format
        """

    @property
    def objects(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Object]:
        """
        sequence of detected objects
        """

    @property
    def fov(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TypeMetrics]:
        """
        fov metrics
        """

    @property
    def rois(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TypeMetrics]:
        """
        ROI based object count
        """

    @property
    def socialDistancing(self) -> global___SD: ...
    @property
    def segmentation(self) -> global___Segmentation:
        """
        Panoptic segmentation mask
        """

    @property
    def interactions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Interaction]:
        """
        interactions between objects
        """

    @property
    def congestions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Congestion]:
        """
        congestion on floors, etc
        """

    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """
        info, generic attr=value for any customization
        """

    def __init__(
        self,
        *,
        version: builtins.str = ...,
        id: builtins.str = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        sensorId: builtins.str = ...,
        objects: collections.abc.Iterable[global___Object] | None = ...,
        fov: collections.abc.Iterable[global___TypeMetrics] | None = ...,
        rois: collections.abc.Iterable[global___TypeMetrics] | None = ...,
        socialDistancing: global___SD | None = ...,
        segmentation: global___Segmentation | None = ...,
        interactions: collections.abc.Iterable[global___Interaction] | None = ...,
        congestions: collections.abc.Iterable[global___Congestion] | None = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["segmentation", b"segmentation", "socialDistancing", b"socialDistancing", "timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["congestions", b"congestions", "fov", b"fov", "id", b"id", "info", b"info", "interactions", b"interactions", "objects", b"objects", "rois", b"rois", "segmentation", b"segmentation", "sensorId", b"sensorId", "socialDistancing", b"socialDistancing", "timestamp", b"timestamp", "version", b"version"]) -> None: ...

global___Frame = Frame

@typing.final
class Object(google.protobuf.message.Message):
    """
    represents detected object in a given frame, most of the attributes in an Object are optional
    and is dictated by the inference model pipeline. Object id, bbox, type and confidence is muust have, rest is optional
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    BBOX_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    EMBEDDING_FIELD_NUMBER: builtins.int
    POSE_FIELD_NUMBER: builtins.int
    GAZE_FIELD_NUMBER: builtins.int
    LIPACTIVITY_FIELD_NUMBER: builtins.int
    SPEED_FIELD_NUMBER: builtins.int
    DIR_FIELD_NUMBER: builtins.int
    COORDINATE_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    BBOX3D_FIELD_NUMBER: builtins.int
    id: builtins.str
    """
    object ID
    """
    type: builtins.str
    """
    type of object, example Person, Vehicle, Face
    """
    confidence: builtins.float
    """
    confidence
    """
    speed: builtins.float
    """
    speed of object
    """
    @property
    def bbox(self) -> global___Bbox:
        """
        detection bbox
        """

    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """
        map of attributes, name:value pair. example secondary attributes for vehicle would are color, make etc
        when a person is detected it will height, eye-color etc.
        """

    @property
    def embedding(self) -> global___Embedding:
        """
        object appearance vector or embedding
        """

    @property
    def pose(self) -> global___Pose:
        """
        object pose, primarily provides array of keypoints
        """

    @property
    def gaze(self) -> global___Gaze:
        """
        gaze, direction and angle of gaze
        """

    @property
    def lipActivity(self) -> global___LipActivity:
        """
        lip activity like speaking, silent
        """

    @property
    def dir(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """
        in direction x, y, z
        """

    @property
    def coordinate(self) -> global___Coordinate:
        """

        cartesian coordinate
        """

    @property
    def location(self) -> global___Location:
        """
        lat, lon, alt
        """

    @property
    def bbox3d(self) -> global___Bbox3d:
        """
        bbox3d, represented using array of 12 coordinates
        """

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        bbox: global___Bbox | None = ...,
        type: builtins.str = ...,
        confidence: builtins.float = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        embedding: global___Embedding | None = ...,
        pose: global___Pose | None = ...,
        gaze: global___Gaze | None = ...,
        lipActivity: global___LipActivity | None = ...,
        speed: builtins.float = ...,
        dir: collections.abc.Iterable[builtins.float] | None = ...,
        coordinate: global___Coordinate | None = ...,
        location: global___Location | None = ...,
        bbox3d: global___Bbox3d | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["bbox", b"bbox", "bbox3d", b"bbox3d", "coordinate", b"coordinate", "embedding", b"embedding", "gaze", b"gaze", "lipActivity", b"lipActivity", "location", b"location", "pose", b"pose"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bbox", b"bbox", "bbox3d", b"bbox3d", "confidence", b"confidence", "coordinate", b"coordinate", "dir", b"dir", "embedding", b"embedding", "gaze", b"gaze", "id", b"id", "info", b"info", "lipActivity", b"lipActivity", "location", b"location", "pose", b"pose", "speed", b"speed", "type", b"type"]) -> None: ...

global___Object = Object

@typing.final
class Coordinate(google.protobuf.message.Message):
    """
    cartesian coordinates
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    z: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
        z: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["x", b"x", "y", b"y", "z", b"z"]) -> None: ...

global___Coordinate = Coordinate

@typing.final
class Location(google.protobuf.message.Message):
    """
    geo location
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LAT_FIELD_NUMBER: builtins.int
    LON_FIELD_NUMBER: builtins.int
    ALT_FIELD_NUMBER: builtins.int
    lat: builtins.float
    lon: builtins.float
    alt: builtins.float
    def __init__(
        self,
        *,
        lat: builtins.float = ...,
        lon: builtins.float = ...,
        alt: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["alt", b"alt", "lat", b"lat", "lon", b"lon"]) -> None: ...

global___Location = Location

@typing.final
class Bbox(google.protobuf.message.Message):
    """
    top left corner + bottom right corner
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    LEFTX_FIELD_NUMBER: builtins.int
    TOPY_FIELD_NUMBER: builtins.int
    RIGHTX_FIELD_NUMBER: builtins.int
    BOTTOMY_FIELD_NUMBER: builtins.int
    EMBEDDINGS_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    leftX: builtins.float
    topY: builtins.float
    rightX: builtins.float
    bottomY: builtins.float
    confidence: builtins.float
    @property
    def embeddings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Embedding]:
        """
        Typically there will be a single array of embeddings representing the characteristics seen in 2d bbox. But there may be situations where multiple embeddings may be used to represent different characteristics of the object
        """

    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        leftX: builtins.float = ...,
        topY: builtins.float = ...,
        rightX: builtins.float = ...,
        bottomY: builtins.float = ...,
        embeddings: collections.abc.Iterable[global___Embedding] | None = ...,
        confidence: builtins.float = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bottomY", b"bottomY", "confidence", b"confidence", "embeddings", b"embeddings", "info", b"info", "leftX", b"leftX", "rightX", b"rightX", "topY", b"topY"]) -> None: ...

global___Bbox = Bbox

@typing.final
class Bbox3d(google.protobuf.message.Message):
    """
    type = Image or Camera
    for Image consider only (x,y), and for Camera (x,y,z)
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    COORDINATES_FIELD_NUMBER: builtins.int
    EMBEDDINGS_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    confidence: builtins.float
    @property
    def coordinates(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """
        The double typed coordinate values will appear in the following order:
        x, y, z, width, length, height, pitch, roll, yaw, vx, vy, vz
        """

    @property
    def embeddings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Embedding]:
        """
        embeddings representing the characteristics as seen in 3d bbox
        """

    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        coordinates: collections.abc.Iterable[builtins.float] | None = ...,
        embeddings: collections.abc.Iterable[global___Embedding] | None = ...,
        confidence: builtins.float = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["confidence", b"confidence", "coordinates", b"coordinates", "embeddings", b"embeddings", "info", b"info"]) -> None: ...

global___Bbox3d = Bbox3d

@typing.final
class Segmentation(google.protobuf.message.Message):
    """
    Segmentation Mask
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    MASK_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    @property
    def mask(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        mask: collections.abc.Iterable[builtins.int] | None = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["info", b"info", "mask", b"mask"]) -> None: ...

global___Segmentation = Segmentation

@typing.final
class TypeMetrics(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    COUNT_FIELD_NUMBER: builtins.int
    COORDINATES_FIELD_NUMBER: builtins.int
    OBJECTIDS_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    id: builtins.str
    """
    roi or fov id, optional for fov
    """
    type: builtins.str
    """
    type of object
    """
    count: builtins.int
    """
    count of object
    """
    @property
    def coordinates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Coordinate]:
        """
        object coordinates
        """

    @property
    def objectIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """
        objects ids
        """

    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """
        optional attributes
        """

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        type: builtins.str = ...,
        count: builtins.int = ...,
        coordinates: collections.abc.Iterable[global___Coordinate] | None = ...,
        objectIds: collections.abc.Iterable[builtins.str] | None = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["coordinates", b"coordinates", "count", b"count", "id", b"id", "info", b"info", "objectIds", b"objectIds", "type", b"type"]) -> None: ...

global___TypeMetrics = TypeMetrics

@typing.final
class Cluster(google.protobuf.message.Message):
    """
    Cluster, array of 2D points
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POINTS_FIELD_NUMBER: builtins.int
    @property
    def points(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Point2D]: ...
    def __init__(
        self,
        *,
        points: collections.abc.Iterable[global___Point2D] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["points", b"points"]) -> None: ...

global___Cluster = Cluster

@typing.final
class Point2D(google.protobuf.message.Message):
    """
    2D point, represented using x,y coordinates
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["x", b"x", "y", b"y"]) -> None: ...

global___Point2D = Point2D

@typing.final
class SD(google.protobuf.message.Message):
    """
    social distancing
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    THRESHOLD_FIELD_NUMBER: builtins.int
    PROXIMITYDETECTIONS_FIELD_NUMBER: builtins.int
    CLUSTERS_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    threshold: builtins.float
    """
    cluster threshold
    """
    proximityDetections: builtins.int
    """
    number of clusters violating social distancing
    """
    @property
    def clusters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Cluster]:
        """
        2D point clusters
        """

    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """
        info, generic attr=value for any customization
        """

    def __init__(
        self,
        *,
        threshold: builtins.float = ...,
        proximityDetections: builtins.int = ...,
        clusters: collections.abc.Iterable[global___Cluster] | None = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["clusters", b"clusters", "info", b"info", "proximityDetections", b"proximityDetections", "threshold", b"threshold"]) -> None: ...

global___SD = SD

@typing.final
class Polygon(google.protobuf.message.Message):
    """
    definition of polygon geometry, equivalent to wkt format.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COORDINATES_FIELD_NUMBER: builtins.int
    HOLES_FIELD_NUMBER: builtins.int
    @property
    def coordinates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Point2D]:
        """
        Polygon boundary, equivalent to exterior in wkt format
        """

    @property
    def holes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PolygonHole]:
        """
        Polygon holes, equivalent to interiors in wkt format. Multiple holes can present for one polygon.
        """

    def __init__(
        self,
        *,
        coordinates: collections.abc.Iterable[global___Point2D] | None = ...,
        holes: collections.abc.Iterable[global___PolygonHole] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["coordinates", b"coordinates", "holes", b"holes"]) -> None: ...

global___Polygon = Polygon

@typing.final
class PolygonHole(google.protobuf.message.Message):
    """
    definition of polygon hole.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COORDINATES_FIELD_NUMBER: builtins.int
    @property
    def coordinates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Point2D]:
        """
        polygon hole, equivalent to polygon's interior in wkt format
        """

    def __init__(
        self,
        *,
        coordinates: collections.abc.Iterable[global___Point2D] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["coordinates", b"coordinates"]) -> None: ...

global___PolygonHole = PolygonHole

@typing.final
class Interaction(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    OBJECTIDS_FIELD_NUMBER: builtins.int
    COORDINATES_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    id: builtins.str
    """
    id
    """
    description: builtins.str
    """
    description, example person interacting with a box
    """
    @property
    def objectIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """
        objects ids
        """

    @property
    def coordinates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Coordinate]:
        """
        object coordinates
        """

    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """
        optional attributes
        """

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        objectIds: collections.abc.Iterable[builtins.str] | None = ...,
        coordinates: collections.abc.Iterable[global___Coordinate] | None = ...,
        description: builtins.str = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["coordinates", b"coordinates", "description", b"description", "id", b"id", "info", b"info", "objectIds", b"objectIds"]) -> None: ...

global___Interaction = Interaction

@typing.final
class Congestion(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    OBJECTIDS_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    id: builtins.str
    """
    optional id
    """
    amount: builtins.float
    """
    amount values between 0 and 1, use segmentation mask to calculate
    """
    @property
    def objectIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """
        objects ids
        """

    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """
        optional attributes
        """

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        objectIds: collections.abc.Iterable[builtins.str] | None = ...,
        amount: builtins.float = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["amount", b"amount", "id", b"id", "info", b"info", "objectIds", b"objectIds"]) -> None: ...

global___Congestion = Congestion

@typing.final
class Pose(google.protobuf.message.Message):
    """
    The type represent the  nature of the pose,
    i.e., pose2D, pose25D or pose3D,

    which is followed by several Keypoints or bodyparts.
    Each Keypoint comprises of

    -name,

    -coordinate (x,y,z, confidence)

    -quaternion (qx,qy,qz,qw), quaternion values are optional.

    - e.g., |left-eye|x,y,z,0.75|qx,qy,qz,qw|.

    -For pose3D, the coordinates (x,y,z) are in the world coordinate system with
    respect to the camera (unit: mm).

    -For pose2.5D, it shares the same format as pose3D,
    however, the coordinates (x,y) are in the image plane (unit: pixel) and the z coordinate
    stands for the metric depth relative to the root keypoint, i.e., pelvis (unit: mm).

    -For pose2D, (x,y) are the image pixel coordinates and the z coordinate is ignored, e.g., |right-ear,x,y,0.0.0.80|.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class Keypoint(google.protobuf.message.Message):
        """
        Keypoint + quaternion
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        COORDINATES_FIELD_NUMBER: builtins.int
        QUATERNION_FIELD_NUMBER: builtins.int
        name: builtins.str
        """name of keypoint"""
        @property
        def coordinates(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
            """Array comprising of (x,y,z, confidence)"""

        @property
        def quaternion(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
            """Array comprising of (qx,qy,qz,qw)"""

        def __init__(
            self,
            *,
            name: builtins.str = ...,
            coordinates: collections.abc.Iterable[builtins.float] | None = ...,
            quaternion: collections.abc.Iterable[builtins.float] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["coordinates", b"coordinates", "name", b"name", "quaternion", b"quaternion"]) -> None: ...

    @typing.final
    class Action(google.protobuf.message.Message):
        """
        Pose Action, like walking, running
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TYPE_FIELD_NUMBER: builtins.int
        CONFIDENCE_FIELD_NUMBER: builtins.int
        type: builtins.str
        """
        type of action, standing, running etc
        """
        confidence: builtins.float
        """
        confidence of actions
        """
        def __init__(
            self,
            *,
            type: builtins.str = ...,
            confidence: builtins.float = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["confidence", b"confidence", "type", b"type"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    KEYPOINTS_FIELD_NUMBER: builtins.int
    ACTIONS_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    type: builtins.str
    """
    pose2D or pose3D or pose25D
    """
    @property
    def keypoints(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Pose.Keypoint]:
        """
        array of keypoints
        """

    @property
    def actions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Pose.Action]:
        """
        array of pose actons with their probabilities or confidence
        """

    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """
        optional attributes
        """

    def __init__(
        self,
        *,
        type: builtins.str = ...,
        keypoints: collections.abc.Iterable[global___Pose.Keypoint] | None = ...,
        actions: collections.abc.Iterable[global___Pose.Action] | None = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["actions", b"actions", "info", b"info", "keypoints", b"keypoints", "type", b"type"]) -> None: ...

global___Pose = Pose

@typing.final
class Gaze(google.protobuf.message.Message):
    """
    Gaze point of reference  x,y,z are in the camera coordinate system.
    theta, phi are angles
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    THETA_FIELD_NUMBER: builtins.int
    PHI_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    z: builtins.float
    theta: builtins.float
    phi: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
        z: builtins.float = ...,
        theta: builtins.float = ...,
        phi: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["phi", b"phi", "theta", b"theta", "x", b"x", "y", b"y", "z", b"z"]) -> None: ...

global___Gaze = Gaze

@typing.final
class LipActivity(google.protobuf.message.Message):
    """
    activity like silent speaking
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLASSLABEL_FIELD_NUMBER: builtins.int
    classLabel: builtins.str
    def __init__(
        self,
        *,
        classLabel: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["classLabel", b"classLabel"]) -> None: ...

global___LipActivity = LipActivity

@typing.final
class Event(google.protobuf.message.Message):
    """
    event like moving, parked, etc
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    id: builtins.str
    """
    id
    """
    type: builtins.str
    """
    type
    """
    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """
        optional attributes
        """

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        type: builtins.str = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "info", b"info", "type", b"type"]) -> None: ...

global___Event = Event

@typing.final
class AnalyticsModule(google.protobuf.message.Message):
    """

    Analytics Module to be nested in every message, example below

    {{{


    "analyticsModule": {
    			"id": "module-id",
    			"description": "Vehicle Detection and License Plate Recognition",
    			"source": "OpenALR",
    			"version": "3.0"
    }


    }}}
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    id: builtins.str
    """
    id
    """
    description: builtins.str
    """
    description
    """
    source: builtins.str
    """
    source
    """
    version: builtins.str
    """
    version
    """
    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """
        additional info
        """

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        description: builtins.str = ...,
        source: builtins.str = ...,
        version: builtins.str = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["description", b"description", "id", b"id", "info", b"info", "source", b"source", "version", b"version"]) -> None: ...

global___AnalyticsModule = AnalyticsModule

@typing.final
class Sensor(google.protobuf.message.Message):
    """

    Sensor object to be nested in every message, example

    {{{


    "sensor": {
    		"id": "string",
    		"type": "Camera/Puck",
    		"location": {
    			  "lat": 45.99,
    			  "lon": 35.54,
    			  "alt": 79.03
         },
        "coordinate": {
    			   "x": 5.2,
    			  "y": 10.1,
    			  "z": 11.2
         },
         "description": "Entrance of Endeavor Garage Right Lane"
    }


    }}}
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    COORDINATE_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    id: builtins.str
    """
    id
    """
    type: builtins.str
    """
    Camera or Puck
    """
    description: builtins.str
    """
    description
    """
    @property
    def location(self) -> global___Location:
        """
        in lat, lon, alt
        """

    @property
    def coordinate(self) -> global___Coordinate:
        """
        in x,y,z
        """

    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """
        additional info
        """

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        type: builtins.str = ...,
        description: builtins.str = ...,
        location: global___Location | None = ...,
        coordinate: global___Coordinate | None = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["coordinate", b"coordinate", "location", b"location"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["coordinate", b"coordinate", "description", b"description", "id", b"id", "info", b"info", "location", b"location", "type", b"type"]) -> None: ...

global___Sensor = Sensor

@typing.final
class Place(google.protobuf.message.Message):
    """

    Describing a scene needs describing where the scene is happening – place,
    what is happening in terms of events, and who are the objects participating in the event.
    note coordinate(x,y,z) are in meters

    Json representation of Place
    {{{


    "place": {
    "id": "string",
    "name": "endeavor",
    "type": "building/garage",
    "location": {
    "lat": 37.37060687475246,
    "lon": -121.9672466762127,
    "alt": 0.00
    }


    }}}
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    COORDINATE_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    id: builtins.str
    """
    Id
    """
    name: builtins.str
    """
    name
    """
    type: builtins.str
    """
    Parking Lot or Entrance or Room
    """
    @property
    def location(self) -> global___Location:
        """
        in lat, lon, alt
        """

    @property
    def coordinate(self) -> global___Coordinate:
        """
        in x,y,z
        """

    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """
        additional info, example details of park lot
        """

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        name: builtins.str = ...,
        type: builtins.str = ...,
        location: global___Location | None = ...,
        coordinate: global___Coordinate | None = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["coordinate", b"coordinate", "location", b"location"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["coordinate", b"coordinate", "id", b"id", "info", b"info", "location", b"location", "name", b"name", "type", b"type"]) -> None: ...

global___Place = Place

@typing.final
class Message(google.protobuf.message.Message):
    """
    represents a single object detection
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGEID_FIELD_NUMBER: builtins.int
    MDSVERSION_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    PLACE_FIELD_NUMBER: builtins.int
    SENSOR_FIELD_NUMBER: builtins.int
    ANALYTICSMODULE_FIELD_NUMBER: builtins.int
    OBJECT_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    VIDEOPATH_FIELD_NUMBER: builtins.int
    messageid: builtins.str
    mdsversion: builtins.str
    videoPath: builtins.str
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def place(self) -> global___Place: ...
    @property
    def sensor(self) -> global___Sensor: ...
    @property
    def analyticsModule(self) -> global___AnalyticsModule: ...
    @property
    def object(self) -> global___Object: ...
    @property
    def event(self) -> global___Event: ...
    def __init__(
        self,
        *,
        messageid: builtins.str = ...,
        mdsversion: builtins.str = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        place: global___Place | None = ...,
        sensor: global___Sensor | None = ...,
        analyticsModule: global___AnalyticsModule | None = ...,
        object: global___Object | None = ...,
        event: global___Event | None = ...,
        videoPath: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["analyticsModule", b"analyticsModule", "event", b"event", "object", b"object", "place", b"place", "sensor", b"sensor", "timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["analyticsModule", b"analyticsModule", "event", b"event", "mdsversion", b"mdsversion", "messageid", b"messageid", "object", b"object", "place", b"place", "sensor", b"sensor", "timestamp", b"timestamp", "videoPath", b"videoPath"]) -> None: ...

global___Message = Message

@typing.final
class Embedding(google.protobuf.message.Message):
    """
    Embedding
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    VECTOR_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    @property
    def vector(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """
        vector
        """

    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """
        extra info if needed
        """

    def __init__(
        self,
        *,
        vector: collections.abc.Iterable[builtins.float] | None = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["info", b"info", "vector", b"vector"]) -> None: ...

global___Embedding = Embedding

@typing.final
class ImageData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    FORMAT_FIELD_NUMBER: builtins.int
    ENCODING_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    format: global___ImageFormat.ValueType
    encoding: builtins.str
    """RGB, Grayscale"""
    name: builtins.str
    data: builtins.bytes
    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Optional/Custom additional information in Key, Value pair"""

    def __init__(
        self,
        *,
        format: global___ImageFormat.ValueType = ...,
        encoding: builtins.str = ...,
        name: builtins.str = ...,
        data: builtins.bytes = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "encoding", b"encoding", "format", b"format", "info", b"info", "name", b"name"]) -> None: ...

global___ImageData = ImageData

@typing.final
class VisionLLM(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    VERSION_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    STARTFRAMEID_FIELD_NUMBER: builtins.int
    ENDFRAMEID_FIELD_NUMBER: builtins.int
    SENSOR_FIELD_NUMBER: builtins.int
    LLM_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    version: builtins.str
    startFrameId: builtins.str
    """
    start frame id
    """
    endFrameId: builtins.str
    """
    end frame id
    """
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """
        timestamp in UTC format
        """

    @property
    def end(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """
        end timestamp in UTC format
        """

    @property
    def sensor(self) -> global___Sensor:
        """
        sensor, can be camera, video, etc.
        """

    @property
    def llm(self) -> global___LLM:
        """
        LLM query, response, embeddings
        """

    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        version: builtins.str = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        startFrameId: builtins.str = ...,
        endFrameId: builtins.str = ...,
        sensor: global___Sensor | None = ...,
        llm: global___LLM | None = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["end", b"end", "llm", b"llm", "sensor", b"sensor", "timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["end", b"end", "endFrameId", b"endFrameId", "info", b"info", "llm", b"llm", "sensor", b"sensor", "startFrameId", b"startFrameId", "timestamp", b"timestamp", "version", b"version"]) -> None: ...

global___VisionLLM = VisionLLM

@typing.final
class LLM(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    INFO_FIELD_NUMBER: builtins.int
    QUERIES_FIELD_NUMBER: builtins.int
    VISIONEMBEDDINGS_FIELD_NUMBER: builtins.int
    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """
        details of LLM used, like name, version
        """

    @property
    def queries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Query]:
        """
        list of queries
        """

    @property
    def visionEmbeddings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Embedding]:
        """
        representative vision embeddings
        """

    def __init__(
        self,
        *,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        queries: collections.abc.Iterable[global___Query] | None = ...,
        visionEmbeddings: collections.abc.Iterable[global___Embedding] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["info", b"info", "queries", b"queries", "visionEmbeddings", b"visionEmbeddings"]) -> None: ...

global___LLM = LLM

@typing.final
class Query(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ParamsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class PromptsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    PARAMS_FIELD_NUMBER: builtins.int
    PROMPTS_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    EMBEDDINGS_FIELD_NUMBER: builtins.int
    id: builtins.str
    """
    id is optional
    """
    response: builtins.str
    """
    response to query
    """
    @property
    def params(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """
        query params
        """

    @property
    def prompts(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """
        user/system prompts
        """

    @property
    def embeddings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Embedding]:
        """
        optional embedding for query and response
        """

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        params: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        prompts: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        response: builtins.str = ...,
        embeddings: collections.abc.Iterable[global___Embedding] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["embeddings", b"embeddings", "id", b"id", "params", b"params", "prompts", b"prompts", "response", b"response"]) -> None: ...

global___Query = Query
