/*
 * SPDX-FileCopyrightText: Copyright (c) 2023-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include "VideoGeneratorTaskManager.h"
#include <civetweb.h>
#include <fstream>
#include <string>
#include <chrono>

/**
 * This class provides chunked HTTP streaming capability for video files that are actively
 * being generated by the VideoGeneratorTaskManager. It monitors the task status and streams
 * the file content as it becomes available, providing a seamless streaming experience
 * without waiting for complete video generation.
 */
 
class AsyncVideoStreamHandler
{
public:
    AsyncVideoStreamHandler(const std::string& filePath, const std::string& taskId);
    ~AsyncVideoStreamHandler() noexcept;
    
    // Prevent copying and moving (manages file handle resource)
    AsyncVideoStreamHandler(const AsyncVideoStreamHandler&) = delete;
    AsyncVideoStreamHandler& operator=(const AsyncVideoStreamHandler&) = delete;
    AsyncVideoStreamHandler(AsyncVideoStreamHandler&&) = delete;
    AsyncVideoStreamHandler& operator=(AsyncVideoStreamHandler&&) = delete;

    // Check if handler was created successfully
    bool isValid() const noexcept { return isValidHandler; }
    
    int handler(struct mg_connection* conn);

private:
    // Configuration constants
    static constexpr size_t CHUNK_SIZE = 16384;  // 16KB - optimized for video streaming
    static constexpr auto WAIT_FOR_DATA_TIME = std::chrono::milliseconds(500);
    static constexpr auto TASK_STATUS_CACHE_DURATION = std::chrono::seconds(2);
    static constexpr int HTTP_CLIENT_CLOSED_REQUEST = 499;  // Non-standard but widely used for client disconnect

    // Member variables
    std::string filePath;
    std::string taskId;
    std::ifstream file;
    bool isValidHandler{false};

    // Task status caching
    VideoTaskStatus cachedTaskStatus{VideoTaskStatus::PENDING};
    std::chrono::steady_clock::time_point lastStatusCheck;

    // Private helper methods
    bool openFile();
    bool sendHeaders(struct mg_connection* conn);
    static bool sendHttpChunk(struct mg_connection* conn, const void* data, size_t size);
    void closeFileIfOpen() noexcept;
    VideoTaskStatus getTaskStatus();
};
