#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Usage: 
#   - Run directly: ./generate_env.sh [profile1] [profile2]
#   - Source from the test.sh script or cleanup.sh: source generate_env.sh
# This script generates the .env file for the MDX Docker Compose setup

# If script is run directly (not sourced), get SCRIPT_DIR and PROFILE1, PROFILE2
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    # Get the directory where this script is located
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    # Script is being executed directly, process arguments
    PROFILE1=${1:-warehouse_2d}  # Use first argument or default to warehouse_2d
    PROFILE2=${2:-kafka}  # Use second argument or default to kafka
fi

# Parse APP_NAME and APP_MODE from PROFILE1
if [[ "$PROFILE1" == *"_2d" ]]; then
    APP_NAME="${PROFILE1%_2d}"
    APP_MODE="_2d"
elif [[ "$PROFILE1" == *"_3d" ]]; then
    APP_NAME="${PROFILE1%_3d}"
    APP_MODE="_3d"
else
    # For profiles without _2d or _3d suffix (like "smart_city")
    APP_NAME="$PROFILE1"
    APP_MODE=""
fi

# Map test-profile APP_NAME to the source-tree app dir/filename prefix.
# Test fixture dirs stay named after APP_NAME (warehouse_2d, etc.), but the
# Python source lives under apps/<APP_DIR>/main_<APP_DIR><APP_MODE>_app.py.
if [ "$APP_NAME" = "warehouse" ]; then
    APP_DIR="analytics"
else
    APP_DIR="$APP_NAME"
fi

# Set PLAYBACK_MODE based on profile: '--playback-from-json' for 'smart_city', empty otherwise
if [ "$APP_NAME" = "smart_city" ]; then
    PLAYBACK_MODE="--playback-from-json"
else
    PLAYBACK_MODE=""
fi

# Get real IP address
# Use ip first (works on Alpine/BusyBox); hostname -I is not supported on BusyBox
if command -v ip >/dev/null 2>&1; then
    HOST_IP="$(ip route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}')"
fi
if [ -z "$HOST_IP" ]; then
    HOST_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
fi
if [ -z "$HOST_IP" ]; then
    HOST_IP="$(ifconfig 2>/dev/null | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | head -1)"
fi

# If we couldn't get an IP, use localhost as fallback
if [ -z "$HOST_IP" ]; then
    HOST_IP="localhost"
    echo "Warning: Could not determine real IP address, using localhost"
fi

# Create/populate the .env file based on profiles
ENV_FILE="$SCRIPT_DIR/docker_compose/infra/.env"
echo "Generating environment variables at $ENV_FILE"

# Create the .env file with all necessary variables
cat > "$ENV_FILE" << EOF
# Auto-generated environment variables for MDX Docker Compose setup
# Generated by generate_env.sh on $(date)

# Application configuration from PROFILE1: $PROFILE1
APP_NAME="$APP_NAME"
APP_MODE="$APP_MODE"
APP_DIR="$APP_DIR"

# Streaming service from PROFILE2: $PROFILE2
STREAMING_SERVICE="$PROFILE2"

# Playback mode configuration
PLAYBACK_MODE="$PLAYBACK_MODE"

# Path configurations based on SCRIPT_DIR
PROJ_ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
MDX_SAMPLE_APPS_DIR="${SCRIPT_DIR}/docker_compose"
MDX_DATA_DIR="${SCRIPT_DIR}/docker_compose/apps_data"

# Host configuration
HOST_IP="$HOST_IP"

# Volume Creation Variable for appending the volume name
COMPOSE_PROJECT_NAME=mdx
EOF

echo "Generated environment file:"
echo "--------------------------------"
cat "$ENV_FILE"
echo "--------------------------------" 