# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Any, Callable, Dict, List, Optional, Union

from _typeshed import Incomplete

class KafkaError:
    def code(self) -> int: ...
    def name(self) -> str: ...
    def str(self) -> str: ...
    def fatal(self) -> bool: ...
    def retriable(self) -> bool: ...
    def txn_requires_abort(self) -> bool: ...

class Message:
    def topic(self) -> Optional[str]: ...
    def partition(self) -> Optional[int]: ...
    def offset(self) -> Optional[int]: ...
    def key(self) -> Optional[str | bytes]: ...
    def value(self) -> Optional[str | bytes]: ...
    def timestamp(self) -> tuple[int, int]: ...  # (timestamp_type, timestamp)
    def headers(self) -> List[tuple[str, bytes]]: ...
    def error(self) -> Optional[KafkaError]: ...

class Consumer:
    def __init__(self, conf: Dict[str, Any]) -> None: ...
    def subscribe(
        self, topics: Union[str, List[str]], on_assign: Optional[Callable] = None, on_revoke: Optional[Callable] = None
    ) -> None: ...
    def poll(self, timeout: float = 1.0) -> Optional[Message]: ...
    def consume(self, num_messages: int, timeout: float = 0.1) -> List[Message]: ...
    def commit(self, message: Optional[Message] = None, asynchronous: bool = True) -> None: ...
    def close(self) -> None: ...
    def unsubscribe(self) -> None: ...

class Producer:
    def __init__(self, conf: Dict[str, Any]) -> None: ...
    def produce(
        self,
        topic: str,
        value: Optional[bytes] = None,
        key: Optional[bytes] = None,
        partition: int = -1,
        on_delivery: Optional[Callable] = None,
        timestamp: int = 0,
        headers: Optional[List[tuple]] = None,
    ) -> None: ...
    def flush(self, timeout: float = -1) -> int: ...
    def poll(self, timeout: float = 0) -> int: ...

OFFSET_BEGINNING: int
OFFSET_END: int
OFFSET_INVALID: int
OFFSET_STORED: int
TIMESTAMP_CREATE_TIME: int
TIMESTAMP_LOG_APPEND_TIME: int
TIMESTAMP_NOT_AVAILABLE: int
