// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/common/v1/common.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto;
namespace opentelemetry {
namespace proto {
namespace common {
namespace v1 {
class AnyValue;
class AnyValueDefaultTypeInternal;
extern AnyValueDefaultTypeInternal _AnyValue_default_instance_;
class ArrayValue;
class ArrayValueDefaultTypeInternal;
extern ArrayValueDefaultTypeInternal _ArrayValue_default_instance_;
class InstrumentationScope;
class InstrumentationScopeDefaultTypeInternal;
extern InstrumentationScopeDefaultTypeInternal _InstrumentationScope_default_instance_;
class KeyValue;
class KeyValueDefaultTypeInternal;
extern KeyValueDefaultTypeInternal _KeyValue_default_instance_;
class KeyValueList;
class KeyValueListDefaultTypeInternal;
extern KeyValueListDefaultTypeInternal _KeyValueList_default_instance_;
}  // namespace v1
}  // namespace common
}  // namespace proto
}  // namespace opentelemetry
PROTOBUF_NAMESPACE_OPEN
template<> ::opentelemetry::proto::common::v1::AnyValue* Arena::CreateMaybeMessage<::opentelemetry::proto::common::v1::AnyValue>(Arena*);
template<> ::opentelemetry::proto::common::v1::ArrayValue* Arena::CreateMaybeMessage<::opentelemetry::proto::common::v1::ArrayValue>(Arena*);
template<> ::opentelemetry::proto::common::v1::InstrumentationScope* Arena::CreateMaybeMessage<::opentelemetry::proto::common::v1::InstrumentationScope>(Arena*);
template<> ::opentelemetry::proto::common::v1::KeyValue* Arena::CreateMaybeMessage<::opentelemetry::proto::common::v1::KeyValue>(Arena*);
template<> ::opentelemetry::proto::common::v1::KeyValueList* Arena::CreateMaybeMessage<::opentelemetry::proto::common::v1::KeyValueList>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace opentelemetry {
namespace proto {
namespace common {
namespace v1 {

// ===================================================================

class AnyValue PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:opentelemetry.proto.common.v1.AnyValue) */ {
 public:
  inline AnyValue() : AnyValue(nullptr) {};
  virtual ~AnyValue();

  AnyValue(const AnyValue& from);
  AnyValue(AnyValue&& from) noexcept
    : AnyValue() {
    *this = ::std::move(from);
  }

  inline AnyValue& operator=(const AnyValue& from) {
    CopyFrom(from);
    return *this;
  }
  inline AnyValue& operator=(AnyValue&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AnyValue& default_instance();

  enum ValueCase {
    kStringValue = 1,
    kBoolValue = 2,
    kIntValue = 3,
    kDoubleValue = 4,
    kArrayValue = 5,
    kKvlistValue = 6,
    kBytesValue = 7,
    VALUE_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AnyValue* internal_default_instance() {
    return reinterpret_cast<const AnyValue*>(
               &_AnyValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AnyValue& a, AnyValue& b) {
    a.Swap(&b);
  }
  inline void Swap(AnyValue* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AnyValue* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AnyValue* New() const final {
    return CreateMaybeMessage<AnyValue>(nullptr);
  }

  AnyValue* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AnyValue>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AnyValue& from);
  void MergeFrom(const AnyValue& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AnyValue* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "opentelemetry.proto.common.v1.AnyValue";
  }
  protected:
  explicit AnyValue(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto);
    return ::descriptor_table_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStringValueFieldNumber = 1,
    kBoolValueFieldNumber = 2,
    kIntValueFieldNumber = 3,
    kDoubleValueFieldNumber = 4,
    kArrayValueFieldNumber = 5,
    kKvlistValueFieldNumber = 6,
    kBytesValueFieldNumber = 7,
  };
  // string string_value = 1;
  private:
  bool _internal_has_string_value() const;
  public:
  void clear_string_value();
  const std::string& string_value() const;
  void set_string_value(const std::string& value);
  void set_string_value(std::string&& value);
  void set_string_value(const char* value);
  void set_string_value(const char* value, size_t size);
  std::string* mutable_string_value();
  std::string* release_string_value();
  void set_allocated_string_value(std::string* string_value);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_string_value();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_string_value(
      std::string* string_value);
  private:
  const std::string& _internal_string_value() const;
  void _internal_set_string_value(const std::string& value);
  std::string* _internal_mutable_string_value();
  public:

  // bool bool_value = 2;
  private:
  bool _internal_has_bool_value() const;
  public:
  void clear_bool_value();
  bool bool_value() const;
  void set_bool_value(bool value);
  private:
  bool _internal_bool_value() const;
  void _internal_set_bool_value(bool value);
  public:

  // int64 int_value = 3;
  private:
  bool _internal_has_int_value() const;
  public:
  void clear_int_value();
  ::PROTOBUF_NAMESPACE_ID::int64 int_value() const;
  void set_int_value(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_int_value() const;
  void _internal_set_int_value(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // double double_value = 4;
  private:
  bool _internal_has_double_value() const;
  public:
  void clear_double_value();
  double double_value() const;
  void set_double_value(double value);
  private:
  double _internal_double_value() const;
  void _internal_set_double_value(double value);
  public:

  // .opentelemetry.proto.common.v1.ArrayValue array_value = 5;
  bool has_array_value() const;
  private:
  bool _internal_has_array_value() const;
  public:
  void clear_array_value();
  const ::opentelemetry::proto::common::v1::ArrayValue& array_value() const;
  ::opentelemetry::proto::common::v1::ArrayValue* release_array_value();
  ::opentelemetry::proto::common::v1::ArrayValue* mutable_array_value();
  void set_allocated_array_value(::opentelemetry::proto::common::v1::ArrayValue* array_value);
  private:
  const ::opentelemetry::proto::common::v1::ArrayValue& _internal_array_value() const;
  ::opentelemetry::proto::common::v1::ArrayValue* _internal_mutable_array_value();
  public:
  void unsafe_arena_set_allocated_array_value(
      ::opentelemetry::proto::common::v1::ArrayValue* array_value);
  ::opentelemetry::proto::common::v1::ArrayValue* unsafe_arena_release_array_value();

  // .opentelemetry.proto.common.v1.KeyValueList kvlist_value = 6;
  bool has_kvlist_value() const;
  private:
  bool _internal_has_kvlist_value() const;
  public:
  void clear_kvlist_value();
  const ::opentelemetry::proto::common::v1::KeyValueList& kvlist_value() const;
  ::opentelemetry::proto::common::v1::KeyValueList* release_kvlist_value();
  ::opentelemetry::proto::common::v1::KeyValueList* mutable_kvlist_value();
  void set_allocated_kvlist_value(::opentelemetry::proto::common::v1::KeyValueList* kvlist_value);
  private:
  const ::opentelemetry::proto::common::v1::KeyValueList& _internal_kvlist_value() const;
  ::opentelemetry::proto::common::v1::KeyValueList* _internal_mutable_kvlist_value();
  public:
  void unsafe_arena_set_allocated_kvlist_value(
      ::opentelemetry::proto::common::v1::KeyValueList* kvlist_value);
  ::opentelemetry::proto::common::v1::KeyValueList* unsafe_arena_release_kvlist_value();

  // bytes bytes_value = 7;
  private:
  bool _internal_has_bytes_value() const;
  public:
  void clear_bytes_value();
  const std::string& bytes_value() const;
  void set_bytes_value(const std::string& value);
  void set_bytes_value(std::string&& value);
  void set_bytes_value(const char* value);
  void set_bytes_value(const void* value, size_t size);
  std::string* mutable_bytes_value();
  std::string* release_bytes_value();
  void set_allocated_bytes_value(std::string* bytes_value);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_bytes_value();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_bytes_value(
      std::string* bytes_value);
  private:
  const std::string& _internal_bytes_value() const;
  void _internal_set_bytes_value(const std::string& value);
  std::string* _internal_mutable_bytes_value();
  public:

  void clear_value();
  ValueCase value_case() const;
  // @@protoc_insertion_point(class_scope:opentelemetry.proto.common.v1.AnyValue)
 private:
  class _Internal;
  void set_has_string_value();
  void set_has_bool_value();
  void set_has_int_value();
  void set_has_double_value();
  void set_has_array_value();
  void set_has_kvlist_value();
  void set_has_bytes_value();

  inline bool has_value() const;
  inline void clear_has_value();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  union ValueUnion {
    ValueUnion() {}
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr string_value_;
    bool bool_value_;
    ::PROTOBUF_NAMESPACE_ID::int64 int_value_;
    double double_value_;
    ::opentelemetry::proto::common::v1::ArrayValue* array_value_;
    ::opentelemetry::proto::common::v1::KeyValueList* kvlist_value_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bytes_value_;
  } value_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto;
};
// -------------------------------------------------------------------

class ArrayValue PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:opentelemetry.proto.common.v1.ArrayValue) */ {
 public:
  inline ArrayValue() : ArrayValue(nullptr) {};
  virtual ~ArrayValue();

  ArrayValue(const ArrayValue& from);
  ArrayValue(ArrayValue&& from) noexcept
    : ArrayValue() {
    *this = ::std::move(from);
  }

  inline ArrayValue& operator=(const ArrayValue& from) {
    CopyFrom(from);
    return *this;
  }
  inline ArrayValue& operator=(ArrayValue&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ArrayValue& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ArrayValue* internal_default_instance() {
    return reinterpret_cast<const ArrayValue*>(
               &_ArrayValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ArrayValue& a, ArrayValue& b) {
    a.Swap(&b);
  }
  inline void Swap(ArrayValue* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ArrayValue* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ArrayValue* New() const final {
    return CreateMaybeMessage<ArrayValue>(nullptr);
  }

  ArrayValue* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ArrayValue>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ArrayValue& from);
  void MergeFrom(const ArrayValue& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ArrayValue* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "opentelemetry.proto.common.v1.ArrayValue";
  }
  protected:
  explicit ArrayValue(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto);
    return ::descriptor_table_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValuesFieldNumber = 1,
  };
  // repeated .opentelemetry.proto.common.v1.AnyValue values = 1;
  int values_size() const;
  private:
  int _internal_values_size() const;
  public:
  void clear_values();
  ::opentelemetry::proto::common::v1::AnyValue* mutable_values(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::AnyValue >*
      mutable_values();
  private:
  const ::opentelemetry::proto::common::v1::AnyValue& _internal_values(int index) const;
  ::opentelemetry::proto::common::v1::AnyValue* _internal_add_values();
  public:
  const ::opentelemetry::proto::common::v1::AnyValue& values(int index) const;
  ::opentelemetry::proto::common::v1::AnyValue* add_values();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::AnyValue >&
      values() const;

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.common.v1.ArrayValue)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::AnyValue > values_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto;
};
// -------------------------------------------------------------------

class KeyValueList PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:opentelemetry.proto.common.v1.KeyValueList) */ {
 public:
  inline KeyValueList() : KeyValueList(nullptr) {};
  virtual ~KeyValueList();

  KeyValueList(const KeyValueList& from);
  KeyValueList(KeyValueList&& from) noexcept
    : KeyValueList() {
    *this = ::std::move(from);
  }

  inline KeyValueList& operator=(const KeyValueList& from) {
    CopyFrom(from);
    return *this;
  }
  inline KeyValueList& operator=(KeyValueList&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const KeyValueList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const KeyValueList* internal_default_instance() {
    return reinterpret_cast<const KeyValueList*>(
               &_KeyValueList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(KeyValueList& a, KeyValueList& b) {
    a.Swap(&b);
  }
  inline void Swap(KeyValueList* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KeyValueList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline KeyValueList* New() const final {
    return CreateMaybeMessage<KeyValueList>(nullptr);
  }

  KeyValueList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<KeyValueList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const KeyValueList& from);
  void MergeFrom(const KeyValueList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KeyValueList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "opentelemetry.proto.common.v1.KeyValueList";
  }
  protected:
  explicit KeyValueList(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto);
    return ::descriptor_table_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValuesFieldNumber = 1,
  };
  // repeated .opentelemetry.proto.common.v1.KeyValue values = 1;
  int values_size() const;
  private:
  int _internal_values_size() const;
  public:
  void clear_values();
  ::opentelemetry::proto::common::v1::KeyValue* mutable_values(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::KeyValue >*
      mutable_values();
  private:
  const ::opentelemetry::proto::common::v1::KeyValue& _internal_values(int index) const;
  ::opentelemetry::proto::common::v1::KeyValue* _internal_add_values();
  public:
  const ::opentelemetry::proto::common::v1::KeyValue& values(int index) const;
  ::opentelemetry::proto::common::v1::KeyValue* add_values();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::KeyValue >&
      values() const;

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.common.v1.KeyValueList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::KeyValue > values_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto;
};
// -------------------------------------------------------------------

class KeyValue PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:opentelemetry.proto.common.v1.KeyValue) */ {
 public:
  inline KeyValue() : KeyValue(nullptr) {};
  virtual ~KeyValue();

  KeyValue(const KeyValue& from);
  KeyValue(KeyValue&& from) noexcept
    : KeyValue() {
    *this = ::std::move(from);
  }

  inline KeyValue& operator=(const KeyValue& from) {
    CopyFrom(from);
    return *this;
  }
  inline KeyValue& operator=(KeyValue&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const KeyValue& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const KeyValue* internal_default_instance() {
    return reinterpret_cast<const KeyValue*>(
               &_KeyValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(KeyValue& a, KeyValue& b) {
    a.Swap(&b);
  }
  inline void Swap(KeyValue* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KeyValue* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline KeyValue* New() const final {
    return CreateMaybeMessage<KeyValue>(nullptr);
  }

  KeyValue* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<KeyValue>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const KeyValue& from);
  void MergeFrom(const KeyValue& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KeyValue* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "opentelemetry.proto.common.v1.KeyValue";
  }
  protected:
  explicit KeyValue(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto);
    return ::descriptor_table_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // string key = 1;
  void clear_key();
  const std::string& key() const;
  void set_key(const std::string& value);
  void set_key(std::string&& value);
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  std::string* mutable_key();
  std::string* release_key();
  void set_allocated_key(std::string* key);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_key();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_key(
      std::string* key);
  private:
  const std::string& _internal_key() const;
  void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // .opentelemetry.proto.common.v1.AnyValue value = 2;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  const ::opentelemetry::proto::common::v1::AnyValue& value() const;
  ::opentelemetry::proto::common::v1::AnyValue* release_value();
  ::opentelemetry::proto::common::v1::AnyValue* mutable_value();
  void set_allocated_value(::opentelemetry::proto::common::v1::AnyValue* value);
  private:
  const ::opentelemetry::proto::common::v1::AnyValue& _internal_value() const;
  ::opentelemetry::proto::common::v1::AnyValue* _internal_mutable_value();
  public:
  void unsafe_arena_set_allocated_value(
      ::opentelemetry::proto::common::v1::AnyValue* value);
  ::opentelemetry::proto::common::v1::AnyValue* unsafe_arena_release_value();

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.common.v1.KeyValue)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
  ::opentelemetry::proto::common::v1::AnyValue* value_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto;
};
// -------------------------------------------------------------------

class InstrumentationScope PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:opentelemetry.proto.common.v1.InstrumentationScope) */ {
 public:
  inline InstrumentationScope() : InstrumentationScope(nullptr) {};
  virtual ~InstrumentationScope();

  InstrumentationScope(const InstrumentationScope& from);
  InstrumentationScope(InstrumentationScope&& from) noexcept
    : InstrumentationScope() {
    *this = ::std::move(from);
  }

  inline InstrumentationScope& operator=(const InstrumentationScope& from) {
    CopyFrom(from);
    return *this;
  }
  inline InstrumentationScope& operator=(InstrumentationScope&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const InstrumentationScope& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InstrumentationScope* internal_default_instance() {
    return reinterpret_cast<const InstrumentationScope*>(
               &_InstrumentationScope_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(InstrumentationScope& a, InstrumentationScope& b) {
    a.Swap(&b);
  }
  inline void Swap(InstrumentationScope* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InstrumentationScope* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline InstrumentationScope* New() const final {
    return CreateMaybeMessage<InstrumentationScope>(nullptr);
  }

  InstrumentationScope* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<InstrumentationScope>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const InstrumentationScope& from);
  void MergeFrom(const InstrumentationScope& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InstrumentationScope* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "opentelemetry.proto.common.v1.InstrumentationScope";
  }
  protected:
  explicit InstrumentationScope(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto);
    return ::descriptor_table_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAttributesFieldNumber = 3,
    kNameFieldNumber = 1,
    kVersionFieldNumber = 2,
    kDroppedAttributesCountFieldNumber = 4,
  };
  // repeated .opentelemetry.proto.common.v1.KeyValue attributes = 3;
  int attributes_size() const;
  private:
  int _internal_attributes_size() const;
  public:
  void clear_attributes();
  ::opentelemetry::proto::common::v1::KeyValue* mutable_attributes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::KeyValue >*
      mutable_attributes();
  private:
  const ::opentelemetry::proto::common::v1::KeyValue& _internal_attributes(int index) const;
  ::opentelemetry::proto::common::v1::KeyValue* _internal_add_attributes();
  public:
  const ::opentelemetry::proto::common::v1::KeyValue& attributes(int index) const;
  ::opentelemetry::proto::common::v1::KeyValue* add_attributes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::KeyValue >&
      attributes() const;

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_name(
      std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string version = 2;
  void clear_version();
  const std::string& version() const;
  void set_version(const std::string& value);
  void set_version(std::string&& value);
  void set_version(const char* value);
  void set_version(const char* value, size_t size);
  std::string* mutable_version();
  std::string* release_version();
  void set_allocated_version(std::string* version);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_version();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_version(
      std::string* version);
  private:
  const std::string& _internal_version() const;
  void _internal_set_version(const std::string& value);
  std::string* _internal_mutable_version();
  public:

  // uint32 dropped_attributes_count = 4;
  void clear_dropped_attributes_count();
  ::PROTOBUF_NAMESPACE_ID::uint32 dropped_attributes_count() const;
  void set_dropped_attributes_count(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_dropped_attributes_count() const;
  void _internal_set_dropped_attributes_count(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.common.v1.InstrumentationScope)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::KeyValue > attributes_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr version_;
  ::PROTOBUF_NAMESPACE_ID::uint32 dropped_attributes_count_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AnyValue

// string string_value = 1;
inline bool AnyValue::_internal_has_string_value() const {
  return value_case() == kStringValue;
}
inline void AnyValue::set_has_string_value() {
  _oneof_case_[0] = kStringValue;
}
inline void AnyValue::clear_string_value() {
  if (_internal_has_string_value()) {
    value_.string_value_.Destroy(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
    clear_has_value();
  }
}
inline const std::string& AnyValue::string_value() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.common.v1.AnyValue.string_value)
  return _internal_string_value();
}
inline void AnyValue::set_string_value(const std::string& value) {
  _internal_set_string_value(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.common.v1.AnyValue.string_value)
}
inline std::string* AnyValue::mutable_string_value() {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.common.v1.AnyValue.string_value)
  return _internal_mutable_string_value();
}
inline const std::string& AnyValue::_internal_string_value() const {
  if (_internal_has_string_value()) {
    return value_.string_value_.Get();
  }
  return *&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void AnyValue::_internal_set_string_value(const std::string& value) {
  if (!_internal_has_string_value()) {
    clear_value();
    set_has_string_value();
    value_.string_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  value_.string_value_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void AnyValue::set_string_value(std::string&& value) {
  // @@protoc_insertion_point(field_set:opentelemetry.proto.common.v1.AnyValue.string_value)
  if (!_internal_has_string_value()) {
    clear_value();
    set_has_string_value();
    value_.string_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  value_.string_value_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:opentelemetry.proto.common.v1.AnyValue.string_value)
}
inline void AnyValue::set_string_value(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  if (!_internal_has_string_value()) {
    clear_value();
    set_has_string_value();
    value_.string_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  value_.string_value_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:opentelemetry.proto.common.v1.AnyValue.string_value)
}
inline void AnyValue::set_string_value(const char* value,
                             size_t size) {
  if (!_internal_has_string_value()) {
    clear_value();
    set_has_string_value();
    value_.string_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  value_.string_value_.Set(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size),
      GetArena());
  // @@protoc_insertion_point(field_set_pointer:opentelemetry.proto.common.v1.AnyValue.string_value)
}
inline std::string* AnyValue::_internal_mutable_string_value() {
  if (!_internal_has_string_value()) {
    clear_value();
    set_has_string_value();
    value_.string_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  return value_.string_value_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* AnyValue::release_string_value() {
  // @@protoc_insertion_point(field_release:opentelemetry.proto.common.v1.AnyValue.string_value)
  if (_internal_has_string_value()) {
    clear_has_value();
    return value_.string_value_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  } else {
    return nullptr;
  }
}
inline void AnyValue::set_allocated_string_value(std::string* string_value) {
  if (has_value()) {
    clear_value();
  }
  if (string_value != nullptr) {
    set_has_string_value();
    value_.string_value_.UnsafeSetDefault(string_value);
  }
  // @@protoc_insertion_point(field_set_allocated:opentelemetry.proto.common.v1.AnyValue.string_value)
}
inline std::string* AnyValue::unsafe_arena_release_string_value() {
  // @@protoc_insertion_point(field_unsafe_arena_release:opentelemetry.proto.common.v1.AnyValue.string_value)
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (_internal_has_string_value()) {
    clear_has_value();
    return value_.string_value_.UnsafeArenaRelease(
        &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  } else {
    return nullptr;
  }
}
inline void AnyValue::unsafe_arena_set_allocated_string_value(std::string* string_value) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (!_internal_has_string_value()) {
    value_.string_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  clear_value();
  if (string_value) {
    set_has_string_value();
    value_.string_value_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), string_value, GetArena());
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:opentelemetry.proto.common.v1.AnyValue.string_value)
}

// bool bool_value = 2;
inline bool AnyValue::_internal_has_bool_value() const {
  return value_case() == kBoolValue;
}
inline void AnyValue::set_has_bool_value() {
  _oneof_case_[0] = kBoolValue;
}
inline void AnyValue::clear_bool_value() {
  if (_internal_has_bool_value()) {
    value_.bool_value_ = false;
    clear_has_value();
  }
}
inline bool AnyValue::_internal_bool_value() const {
  if (_internal_has_bool_value()) {
    return value_.bool_value_;
  }
  return false;
}
inline void AnyValue::_internal_set_bool_value(bool value) {
  if (!_internal_has_bool_value()) {
    clear_value();
    set_has_bool_value();
  }
  value_.bool_value_ = value;
}
inline bool AnyValue::bool_value() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.common.v1.AnyValue.bool_value)
  return _internal_bool_value();
}
inline void AnyValue::set_bool_value(bool value) {
  _internal_set_bool_value(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.common.v1.AnyValue.bool_value)
}

// int64 int_value = 3;
inline bool AnyValue::_internal_has_int_value() const {
  return value_case() == kIntValue;
}
inline void AnyValue::set_has_int_value() {
  _oneof_case_[0] = kIntValue;
}
inline void AnyValue::clear_int_value() {
  if (_internal_has_int_value()) {
    value_.int_value_ = PROTOBUF_LONGLONG(0);
    clear_has_value();
  }
}
inline ::PROTOBUF_NAMESPACE_ID::int64 AnyValue::_internal_int_value() const {
  if (_internal_has_int_value()) {
    return value_.int_value_;
  }
  return PROTOBUF_LONGLONG(0);
}
inline void AnyValue::_internal_set_int_value(::PROTOBUF_NAMESPACE_ID::int64 value) {
  if (!_internal_has_int_value()) {
    clear_value();
    set_has_int_value();
  }
  value_.int_value_ = value;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 AnyValue::int_value() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.common.v1.AnyValue.int_value)
  return _internal_int_value();
}
inline void AnyValue::set_int_value(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_int_value(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.common.v1.AnyValue.int_value)
}

// double double_value = 4;
inline bool AnyValue::_internal_has_double_value() const {
  return value_case() == kDoubleValue;
}
inline void AnyValue::set_has_double_value() {
  _oneof_case_[0] = kDoubleValue;
}
inline void AnyValue::clear_double_value() {
  if (_internal_has_double_value()) {
    value_.double_value_ = 0;
    clear_has_value();
  }
}
inline double AnyValue::_internal_double_value() const {
  if (_internal_has_double_value()) {
    return value_.double_value_;
  }
  return 0;
}
inline void AnyValue::_internal_set_double_value(double value) {
  if (!_internal_has_double_value()) {
    clear_value();
    set_has_double_value();
  }
  value_.double_value_ = value;
}
inline double AnyValue::double_value() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.common.v1.AnyValue.double_value)
  return _internal_double_value();
}
inline void AnyValue::set_double_value(double value) {
  _internal_set_double_value(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.common.v1.AnyValue.double_value)
}

// .opentelemetry.proto.common.v1.ArrayValue array_value = 5;
inline bool AnyValue::_internal_has_array_value() const {
  return value_case() == kArrayValue;
}
inline bool AnyValue::has_array_value() const {
  return _internal_has_array_value();
}
inline void AnyValue::set_has_array_value() {
  _oneof_case_[0] = kArrayValue;
}
inline void AnyValue::clear_array_value() {
  if (_internal_has_array_value()) {
    if (GetArena() == nullptr) {
      delete value_.array_value_;
    }
    clear_has_value();
  }
}
inline ::opentelemetry::proto::common::v1::ArrayValue* AnyValue::release_array_value() {
  // @@protoc_insertion_point(field_release:opentelemetry.proto.common.v1.AnyValue.array_value)
  if (_internal_has_array_value()) {
    clear_has_value();
      ::opentelemetry::proto::common::v1::ArrayValue* temp = value_.array_value_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    value_.array_value_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::opentelemetry::proto::common::v1::ArrayValue& AnyValue::_internal_array_value() const {
  return _internal_has_array_value()
      ? *value_.array_value_
      : *reinterpret_cast< ::opentelemetry::proto::common::v1::ArrayValue*>(&::opentelemetry::proto::common::v1::_ArrayValue_default_instance_);
}
inline const ::opentelemetry::proto::common::v1::ArrayValue& AnyValue::array_value() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.common.v1.AnyValue.array_value)
  return _internal_array_value();
}
inline ::opentelemetry::proto::common::v1::ArrayValue* AnyValue::unsafe_arena_release_array_value() {
  // @@protoc_insertion_point(field_unsafe_arena_release:opentelemetry.proto.common.v1.AnyValue.array_value)
  if (_internal_has_array_value()) {
    clear_has_value();
    ::opentelemetry::proto::common::v1::ArrayValue* temp = value_.array_value_;
    value_.array_value_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void AnyValue::unsafe_arena_set_allocated_array_value(::opentelemetry::proto::common::v1::ArrayValue* array_value) {
  clear_value();
  if (array_value) {
    set_has_array_value();
    value_.array_value_ = array_value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:opentelemetry.proto.common.v1.AnyValue.array_value)
}
inline ::opentelemetry::proto::common::v1::ArrayValue* AnyValue::_internal_mutable_array_value() {
  if (!_internal_has_array_value()) {
    clear_value();
    set_has_array_value();
    value_.array_value_ = CreateMaybeMessage< ::opentelemetry::proto::common::v1::ArrayValue >(GetArena());
  }
  return value_.array_value_;
}
inline ::opentelemetry::proto::common::v1::ArrayValue* AnyValue::mutable_array_value() {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.common.v1.AnyValue.array_value)
  return _internal_mutable_array_value();
}

// .opentelemetry.proto.common.v1.KeyValueList kvlist_value = 6;
inline bool AnyValue::_internal_has_kvlist_value() const {
  return value_case() == kKvlistValue;
}
inline bool AnyValue::has_kvlist_value() const {
  return _internal_has_kvlist_value();
}
inline void AnyValue::set_has_kvlist_value() {
  _oneof_case_[0] = kKvlistValue;
}
inline void AnyValue::clear_kvlist_value() {
  if (_internal_has_kvlist_value()) {
    if (GetArena() == nullptr) {
      delete value_.kvlist_value_;
    }
    clear_has_value();
  }
}
inline ::opentelemetry::proto::common::v1::KeyValueList* AnyValue::release_kvlist_value() {
  // @@protoc_insertion_point(field_release:opentelemetry.proto.common.v1.AnyValue.kvlist_value)
  if (_internal_has_kvlist_value()) {
    clear_has_value();
      ::opentelemetry::proto::common::v1::KeyValueList* temp = value_.kvlist_value_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    value_.kvlist_value_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::opentelemetry::proto::common::v1::KeyValueList& AnyValue::_internal_kvlist_value() const {
  return _internal_has_kvlist_value()
      ? *value_.kvlist_value_
      : *reinterpret_cast< ::opentelemetry::proto::common::v1::KeyValueList*>(&::opentelemetry::proto::common::v1::_KeyValueList_default_instance_);
}
inline const ::opentelemetry::proto::common::v1::KeyValueList& AnyValue::kvlist_value() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.common.v1.AnyValue.kvlist_value)
  return _internal_kvlist_value();
}
inline ::opentelemetry::proto::common::v1::KeyValueList* AnyValue::unsafe_arena_release_kvlist_value() {
  // @@protoc_insertion_point(field_unsafe_arena_release:opentelemetry.proto.common.v1.AnyValue.kvlist_value)
  if (_internal_has_kvlist_value()) {
    clear_has_value();
    ::opentelemetry::proto::common::v1::KeyValueList* temp = value_.kvlist_value_;
    value_.kvlist_value_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void AnyValue::unsafe_arena_set_allocated_kvlist_value(::opentelemetry::proto::common::v1::KeyValueList* kvlist_value) {
  clear_value();
  if (kvlist_value) {
    set_has_kvlist_value();
    value_.kvlist_value_ = kvlist_value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:opentelemetry.proto.common.v1.AnyValue.kvlist_value)
}
inline ::opentelemetry::proto::common::v1::KeyValueList* AnyValue::_internal_mutable_kvlist_value() {
  if (!_internal_has_kvlist_value()) {
    clear_value();
    set_has_kvlist_value();
    value_.kvlist_value_ = CreateMaybeMessage< ::opentelemetry::proto::common::v1::KeyValueList >(GetArena());
  }
  return value_.kvlist_value_;
}
inline ::opentelemetry::proto::common::v1::KeyValueList* AnyValue::mutable_kvlist_value() {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.common.v1.AnyValue.kvlist_value)
  return _internal_mutable_kvlist_value();
}

// bytes bytes_value = 7;
inline bool AnyValue::_internal_has_bytes_value() const {
  return value_case() == kBytesValue;
}
inline void AnyValue::set_has_bytes_value() {
  _oneof_case_[0] = kBytesValue;
}
inline void AnyValue::clear_bytes_value() {
  if (_internal_has_bytes_value()) {
    value_.bytes_value_.Destroy(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
    clear_has_value();
  }
}
inline const std::string& AnyValue::bytes_value() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.common.v1.AnyValue.bytes_value)
  return _internal_bytes_value();
}
inline void AnyValue::set_bytes_value(const std::string& value) {
  _internal_set_bytes_value(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.common.v1.AnyValue.bytes_value)
}
inline std::string* AnyValue::mutable_bytes_value() {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.common.v1.AnyValue.bytes_value)
  return _internal_mutable_bytes_value();
}
inline const std::string& AnyValue::_internal_bytes_value() const {
  if (_internal_has_bytes_value()) {
    return value_.bytes_value_.Get();
  }
  return *&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void AnyValue::_internal_set_bytes_value(const std::string& value) {
  if (!_internal_has_bytes_value()) {
    clear_value();
    set_has_bytes_value();
    value_.bytes_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  value_.bytes_value_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void AnyValue::set_bytes_value(std::string&& value) {
  // @@protoc_insertion_point(field_set:opentelemetry.proto.common.v1.AnyValue.bytes_value)
  if (!_internal_has_bytes_value()) {
    clear_value();
    set_has_bytes_value();
    value_.bytes_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  value_.bytes_value_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:opentelemetry.proto.common.v1.AnyValue.bytes_value)
}
inline void AnyValue::set_bytes_value(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  if (!_internal_has_bytes_value()) {
    clear_value();
    set_has_bytes_value();
    value_.bytes_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  value_.bytes_value_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:opentelemetry.proto.common.v1.AnyValue.bytes_value)
}
inline void AnyValue::set_bytes_value(const void* value,
                             size_t size) {
  if (!_internal_has_bytes_value()) {
    clear_value();
    set_has_bytes_value();
    value_.bytes_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  value_.bytes_value_.Set(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size),
      GetArena());
  // @@protoc_insertion_point(field_set_pointer:opentelemetry.proto.common.v1.AnyValue.bytes_value)
}
inline std::string* AnyValue::_internal_mutable_bytes_value() {
  if (!_internal_has_bytes_value()) {
    clear_value();
    set_has_bytes_value();
    value_.bytes_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  return value_.bytes_value_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* AnyValue::release_bytes_value() {
  // @@protoc_insertion_point(field_release:opentelemetry.proto.common.v1.AnyValue.bytes_value)
  if (_internal_has_bytes_value()) {
    clear_has_value();
    return value_.bytes_value_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  } else {
    return nullptr;
  }
}
inline void AnyValue::set_allocated_bytes_value(std::string* bytes_value) {
  if (has_value()) {
    clear_value();
  }
  if (bytes_value != nullptr) {
    set_has_bytes_value();
    value_.bytes_value_.UnsafeSetDefault(bytes_value);
  }
  // @@protoc_insertion_point(field_set_allocated:opentelemetry.proto.common.v1.AnyValue.bytes_value)
}
inline std::string* AnyValue::unsafe_arena_release_bytes_value() {
  // @@protoc_insertion_point(field_unsafe_arena_release:opentelemetry.proto.common.v1.AnyValue.bytes_value)
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (_internal_has_bytes_value()) {
    clear_has_value();
    return value_.bytes_value_.UnsafeArenaRelease(
        &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  } else {
    return nullptr;
  }
}
inline void AnyValue::unsafe_arena_set_allocated_bytes_value(std::string* bytes_value) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (!_internal_has_bytes_value()) {
    value_.bytes_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  clear_value();
  if (bytes_value) {
    set_has_bytes_value();
    value_.bytes_value_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), bytes_value, GetArena());
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:opentelemetry.proto.common.v1.AnyValue.bytes_value)
}

inline bool AnyValue::has_value() const {
  return value_case() != VALUE_NOT_SET;
}
inline void AnyValue::clear_has_value() {
  _oneof_case_[0] = VALUE_NOT_SET;
}
inline AnyValue::ValueCase AnyValue::value_case() const {
  return AnyValue::ValueCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// ArrayValue

// repeated .opentelemetry.proto.common.v1.AnyValue values = 1;
inline int ArrayValue::_internal_values_size() const {
  return values_.size();
}
inline int ArrayValue::values_size() const {
  return _internal_values_size();
}
inline void ArrayValue::clear_values() {
  values_.Clear();
}
inline ::opentelemetry::proto::common::v1::AnyValue* ArrayValue::mutable_values(int index) {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.common.v1.ArrayValue.values)
  return values_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::AnyValue >*
ArrayValue::mutable_values() {
  // @@protoc_insertion_point(field_mutable_list:opentelemetry.proto.common.v1.ArrayValue.values)
  return &values_;
}
inline const ::opentelemetry::proto::common::v1::AnyValue& ArrayValue::_internal_values(int index) const {
  return values_.Get(index);
}
inline const ::opentelemetry::proto::common::v1::AnyValue& ArrayValue::values(int index) const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.common.v1.ArrayValue.values)
  return _internal_values(index);
}
inline ::opentelemetry::proto::common::v1::AnyValue* ArrayValue::_internal_add_values() {
  return values_.Add();
}
inline ::opentelemetry::proto::common::v1::AnyValue* ArrayValue::add_values() {
  // @@protoc_insertion_point(field_add:opentelemetry.proto.common.v1.ArrayValue.values)
  return _internal_add_values();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::AnyValue >&
ArrayValue::values() const {
  // @@protoc_insertion_point(field_list:opentelemetry.proto.common.v1.ArrayValue.values)
  return values_;
}

// -------------------------------------------------------------------

// KeyValueList

// repeated .opentelemetry.proto.common.v1.KeyValue values = 1;
inline int KeyValueList::_internal_values_size() const {
  return values_.size();
}
inline int KeyValueList::values_size() const {
  return _internal_values_size();
}
inline void KeyValueList::clear_values() {
  values_.Clear();
}
inline ::opentelemetry::proto::common::v1::KeyValue* KeyValueList::mutable_values(int index) {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.common.v1.KeyValueList.values)
  return values_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::KeyValue >*
KeyValueList::mutable_values() {
  // @@protoc_insertion_point(field_mutable_list:opentelemetry.proto.common.v1.KeyValueList.values)
  return &values_;
}
inline const ::opentelemetry::proto::common::v1::KeyValue& KeyValueList::_internal_values(int index) const {
  return values_.Get(index);
}
inline const ::opentelemetry::proto::common::v1::KeyValue& KeyValueList::values(int index) const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.common.v1.KeyValueList.values)
  return _internal_values(index);
}
inline ::opentelemetry::proto::common::v1::KeyValue* KeyValueList::_internal_add_values() {
  return values_.Add();
}
inline ::opentelemetry::proto::common::v1::KeyValue* KeyValueList::add_values() {
  // @@protoc_insertion_point(field_add:opentelemetry.proto.common.v1.KeyValueList.values)
  return _internal_add_values();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::KeyValue >&
KeyValueList::values() const {
  // @@protoc_insertion_point(field_list:opentelemetry.proto.common.v1.KeyValueList.values)
  return values_;
}

// -------------------------------------------------------------------

// KeyValue

// string key = 1;
inline void KeyValue::clear_key() {
  key_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& KeyValue::key() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.common.v1.KeyValue.key)
  return _internal_key();
}
inline void KeyValue::set_key(const std::string& value) {
  _internal_set_key(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.common.v1.KeyValue.key)
}
inline std::string* KeyValue::mutable_key() {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.common.v1.KeyValue.key)
  return _internal_mutable_key();
}
inline const std::string& KeyValue::_internal_key() const {
  return key_.Get();
}
inline void KeyValue::_internal_set_key(const std::string& value) {
  
  key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void KeyValue::set_key(std::string&& value) {
  
  key_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:opentelemetry.proto.common.v1.KeyValue.key)
}
inline void KeyValue::set_key(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:opentelemetry.proto.common.v1.KeyValue.key)
}
inline void KeyValue::set_key(const char* value,
    size_t size) {
  
  key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:opentelemetry.proto.common.v1.KeyValue.key)
}
inline std::string* KeyValue::_internal_mutable_key() {
  
  return key_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* KeyValue::release_key() {
  // @@protoc_insertion_point(field_release:opentelemetry.proto.common.v1.KeyValue.key)
  return key_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void KeyValue::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  key_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), key,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:opentelemetry.proto.common.v1.KeyValue.key)
}
inline std::string* KeyValue::unsafe_arena_release_key() {
  // @@protoc_insertion_point(field_unsafe_arena_release:opentelemetry.proto.common.v1.KeyValue.key)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return key_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void KeyValue::unsafe_arena_set_allocated_key(
    std::string* key) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (key != nullptr) {
    
  } else {
    
  }
  key_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      key, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:opentelemetry.proto.common.v1.KeyValue.key)
}

// .opentelemetry.proto.common.v1.AnyValue value = 2;
inline bool KeyValue::_internal_has_value() const {
  return this != internal_default_instance() && value_ != nullptr;
}
inline bool KeyValue::has_value() const {
  return _internal_has_value();
}
inline void KeyValue::clear_value() {
  if (GetArena() == nullptr && value_ != nullptr) {
    delete value_;
  }
  value_ = nullptr;
}
inline const ::opentelemetry::proto::common::v1::AnyValue& KeyValue::_internal_value() const {
  const ::opentelemetry::proto::common::v1::AnyValue* p = value_;
  return p != nullptr ? *p : *reinterpret_cast<const ::opentelemetry::proto::common::v1::AnyValue*>(
      &::opentelemetry::proto::common::v1::_AnyValue_default_instance_);
}
inline const ::opentelemetry::proto::common::v1::AnyValue& KeyValue::value() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.common.v1.KeyValue.value)
  return _internal_value();
}
inline void KeyValue::unsafe_arena_set_allocated_value(
    ::opentelemetry::proto::common::v1::AnyValue* value) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(value_);
  }
  value_ = value;
  if (value) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:opentelemetry.proto.common.v1.KeyValue.value)
}
inline ::opentelemetry::proto::common::v1::AnyValue* KeyValue::release_value() {
  auto temp = unsafe_arena_release_value();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::opentelemetry::proto::common::v1::AnyValue* KeyValue::unsafe_arena_release_value() {
  // @@protoc_insertion_point(field_release:opentelemetry.proto.common.v1.KeyValue.value)
  
  ::opentelemetry::proto::common::v1::AnyValue* temp = value_;
  value_ = nullptr;
  return temp;
}
inline ::opentelemetry::proto::common::v1::AnyValue* KeyValue::_internal_mutable_value() {
  
  if (value_ == nullptr) {
    auto* p = CreateMaybeMessage<::opentelemetry::proto::common::v1::AnyValue>(GetArena());
    value_ = p;
  }
  return value_;
}
inline ::opentelemetry::proto::common::v1::AnyValue* KeyValue::mutable_value() {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.common.v1.KeyValue.value)
  return _internal_mutable_value();
}
inline void KeyValue::set_allocated_value(::opentelemetry::proto::common::v1::AnyValue* value) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete value_;
  }
  if (value) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(value);
    if (message_arena != submessage_arena) {
      value = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, value, submessage_arena);
    }
    
  } else {
    
  }
  value_ = value;
  // @@protoc_insertion_point(field_set_allocated:opentelemetry.proto.common.v1.KeyValue.value)
}

// -------------------------------------------------------------------

// InstrumentationScope

// string name = 1;
inline void InstrumentationScope::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& InstrumentationScope::name() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.common.v1.InstrumentationScope.name)
  return _internal_name();
}
inline void InstrumentationScope::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.common.v1.InstrumentationScope.name)
}
inline std::string* InstrumentationScope::mutable_name() {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.common.v1.InstrumentationScope.name)
  return _internal_mutable_name();
}
inline const std::string& InstrumentationScope::_internal_name() const {
  return name_.Get();
}
inline void InstrumentationScope::_internal_set_name(const std::string& value) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void InstrumentationScope::set_name(std::string&& value) {
  
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:opentelemetry.proto.common.v1.InstrumentationScope.name)
}
inline void InstrumentationScope::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:opentelemetry.proto.common.v1.InstrumentationScope.name)
}
inline void InstrumentationScope::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:opentelemetry.proto.common.v1.InstrumentationScope.name)
}
inline std::string* InstrumentationScope::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* InstrumentationScope::release_name() {
  // @@protoc_insertion_point(field_release:opentelemetry.proto.common.v1.InstrumentationScope.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void InstrumentationScope::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:opentelemetry.proto.common.v1.InstrumentationScope.name)
}
inline std::string* InstrumentationScope::unsafe_arena_release_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:opentelemetry.proto.common.v1.InstrumentationScope.name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void InstrumentationScope::unsafe_arena_set_allocated_name(
    std::string* name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (name != nullptr) {
    
  } else {
    
  }
  name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:opentelemetry.proto.common.v1.InstrumentationScope.name)
}

// string version = 2;
inline void InstrumentationScope::clear_version() {
  version_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& InstrumentationScope::version() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.common.v1.InstrumentationScope.version)
  return _internal_version();
}
inline void InstrumentationScope::set_version(const std::string& value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.common.v1.InstrumentationScope.version)
}
inline std::string* InstrumentationScope::mutable_version() {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.common.v1.InstrumentationScope.version)
  return _internal_mutable_version();
}
inline const std::string& InstrumentationScope::_internal_version() const {
  return version_.Get();
}
inline void InstrumentationScope::_internal_set_version(const std::string& value) {
  
  version_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void InstrumentationScope::set_version(std::string&& value) {
  
  version_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:opentelemetry.proto.common.v1.InstrumentationScope.version)
}
inline void InstrumentationScope::set_version(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  version_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:opentelemetry.proto.common.v1.InstrumentationScope.version)
}
inline void InstrumentationScope::set_version(const char* value,
    size_t size) {
  
  version_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:opentelemetry.proto.common.v1.InstrumentationScope.version)
}
inline std::string* InstrumentationScope::_internal_mutable_version() {
  
  return version_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* InstrumentationScope::release_version() {
  // @@protoc_insertion_point(field_release:opentelemetry.proto.common.v1.InstrumentationScope.version)
  return version_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void InstrumentationScope::set_allocated_version(std::string* version) {
  if (version != nullptr) {
    
  } else {
    
  }
  version_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), version,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:opentelemetry.proto.common.v1.InstrumentationScope.version)
}
inline std::string* InstrumentationScope::unsafe_arena_release_version() {
  // @@protoc_insertion_point(field_unsafe_arena_release:opentelemetry.proto.common.v1.InstrumentationScope.version)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return version_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void InstrumentationScope::unsafe_arena_set_allocated_version(
    std::string* version) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (version != nullptr) {
    
  } else {
    
  }
  version_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      version, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:opentelemetry.proto.common.v1.InstrumentationScope.version)
}

// repeated .opentelemetry.proto.common.v1.KeyValue attributes = 3;
inline int InstrumentationScope::_internal_attributes_size() const {
  return attributes_.size();
}
inline int InstrumentationScope::attributes_size() const {
  return _internal_attributes_size();
}
inline void InstrumentationScope::clear_attributes() {
  attributes_.Clear();
}
inline ::opentelemetry::proto::common::v1::KeyValue* InstrumentationScope::mutable_attributes(int index) {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.common.v1.InstrumentationScope.attributes)
  return attributes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::KeyValue >*
InstrumentationScope::mutable_attributes() {
  // @@protoc_insertion_point(field_mutable_list:opentelemetry.proto.common.v1.InstrumentationScope.attributes)
  return &attributes_;
}
inline const ::opentelemetry::proto::common::v1::KeyValue& InstrumentationScope::_internal_attributes(int index) const {
  return attributes_.Get(index);
}
inline const ::opentelemetry::proto::common::v1::KeyValue& InstrumentationScope::attributes(int index) const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.common.v1.InstrumentationScope.attributes)
  return _internal_attributes(index);
}
inline ::opentelemetry::proto::common::v1::KeyValue* InstrumentationScope::_internal_add_attributes() {
  return attributes_.Add();
}
inline ::opentelemetry::proto::common::v1::KeyValue* InstrumentationScope::add_attributes() {
  // @@protoc_insertion_point(field_add:opentelemetry.proto.common.v1.InstrumentationScope.attributes)
  return _internal_add_attributes();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::KeyValue >&
InstrumentationScope::attributes() const {
  // @@protoc_insertion_point(field_list:opentelemetry.proto.common.v1.InstrumentationScope.attributes)
  return attributes_;
}

// uint32 dropped_attributes_count = 4;
inline void InstrumentationScope::clear_dropped_attributes_count() {
  dropped_attributes_count_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 InstrumentationScope::_internal_dropped_attributes_count() const {
  return dropped_attributes_count_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 InstrumentationScope::dropped_attributes_count() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.common.v1.InstrumentationScope.dropped_attributes_count)
  return _internal_dropped_attributes_count();
}
inline void InstrumentationScope::_internal_set_dropped_attributes_count(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  dropped_attributes_count_ = value;
}
inline void InstrumentationScope::set_dropped_attributes_count(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_dropped_attributes_count(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.common.v1.InstrumentationScope.dropped_attributes_count)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace common
}  // namespace proto
}  // namespace opentelemetry

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_opentelemetry_2fproto_2fcommon_2fv1_2fcommon_2eproto
