// source: ext.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var schema_pb = require('./schema_pb.js');
goog.object.extend(proto, schema_pb);
goog.exportSymbol('proto.nv.Behavior', null, global);
goog.exportSymbol('proto.nv.GeoLocation', null, global);
goog.exportSymbol('proto.nv.GeoLocation.Point', null, global);
goog.exportSymbol('proto.nv.Incident', null, global);
goog.exportSymbol('proto.nv.SpaceUtilization', null, global);
goog.exportSymbol('proto.nv.SpaceUtilizationLayouts', null, global);
goog.exportSymbol('proto.nv.SpaceUtilizationMetrics', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nv.GeoLocation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nv.GeoLocation.repeatedFields_, null);
};
goog.inherits(proto.nv.GeoLocation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nv.GeoLocation.displayName = 'proto.nv.GeoLocation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nv.GeoLocation.Point = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nv.GeoLocation.Point.repeatedFields_, null);
};
goog.inherits(proto.nv.GeoLocation.Point, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nv.GeoLocation.Point.displayName = 'proto.nv.GeoLocation.Point';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nv.Behavior = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nv.Behavior.repeatedFields_, null);
};
goog.inherits(proto.nv.Behavior, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nv.Behavior.displayName = 'proto.nv.Behavior';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nv.Incident = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nv.Incident.repeatedFields_, null);
};
goog.inherits(proto.nv.Incident, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nv.Incident.displayName = 'proto.nv.Incident';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nv.SpaceUtilizationMetrics = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nv.SpaceUtilizationMetrics, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nv.SpaceUtilizationMetrics.displayName = 'proto.nv.SpaceUtilizationMetrics';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nv.SpaceUtilizationLayouts = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nv.SpaceUtilizationLayouts.repeatedFields_, null);
};
goog.inherits(proto.nv.SpaceUtilizationLayouts, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nv.SpaceUtilizationLayouts.displayName = 'proto.nv.SpaceUtilizationLayouts';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nv.SpaceUtilization = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nv.SpaceUtilization.repeatedFields_, null);
};
goog.inherits(proto.nv.SpaceUtilization, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nv.SpaceUtilization.displayName = 'proto.nv.SpaceUtilization';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nv.GeoLocation.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nv.GeoLocation.prototype.toObject = function(opt_includeInstance) {
  return proto.nv.GeoLocation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nv.GeoLocation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nv.GeoLocation.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, ""),
    coordinatesList: jspb.Message.toObjectList(msg.getCoordinatesList(),
    proto.nv.GeoLocation.Point.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nv.GeoLocation}
 */
proto.nv.GeoLocation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nv.GeoLocation;
  return proto.nv.GeoLocation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nv.GeoLocation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nv.GeoLocation}
 */
proto.nv.GeoLocation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 2:
      var value = new proto.nv.GeoLocation.Point;
      reader.readMessage(value,proto.nv.GeoLocation.Point.deserializeBinaryFromReader);
      msg.addCoordinates(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nv.GeoLocation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nv.GeoLocation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nv.GeoLocation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nv.GeoLocation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCoordinatesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.nv.GeoLocation.Point.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nv.GeoLocation.Point.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nv.GeoLocation.Point.prototype.toObject = function(opt_includeInstance) {
  return proto.nv.GeoLocation.Point.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nv.GeoLocation.Point} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nv.GeoLocation.Point.toObject = function(includeInstance, msg) {
  var f, obj = {
    pointList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nv.GeoLocation.Point}
 */
proto.nv.GeoLocation.Point.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nv.GeoLocation.Point;
  return proto.nv.GeoLocation.Point.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nv.GeoLocation.Point} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nv.GeoLocation.Point}
 */
proto.nv.GeoLocation.Point.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addPoint(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nv.GeoLocation.Point.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nv.GeoLocation.Point.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nv.GeoLocation.Point} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nv.GeoLocation.Point.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPointList();
  if (f.length > 0) {
    writer.writePackedDouble(
      1,
      f
    );
  }
};


/**
 * repeated double point = 1;
 * @return {!Array<number>}
 */
proto.nv.GeoLocation.Point.prototype.getPointList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.nv.GeoLocation.Point} returns this
 */
proto.nv.GeoLocation.Point.prototype.setPointList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.nv.GeoLocation.Point} returns this
 */
proto.nv.GeoLocation.Point.prototype.addPoint = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nv.GeoLocation.Point} returns this
 */
proto.nv.GeoLocation.Point.prototype.clearPointList = function() {
  return this.setPointList([]);
};


/**
 * optional string type = 1;
 * @return {string}
 */
proto.nv.GeoLocation.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.nv.GeoLocation} returns this
 */
proto.nv.GeoLocation.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Point coordinates = 2;
 * @return {!Array<!proto.nv.GeoLocation.Point>}
 */
proto.nv.GeoLocation.prototype.getCoordinatesList = function() {
  return /** @type{!Array<!proto.nv.GeoLocation.Point>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.nv.GeoLocation.Point, 2));
};


/**
 * @param {!Array<!proto.nv.GeoLocation.Point>} value
 * @return {!proto.nv.GeoLocation} returns this
*/
proto.nv.GeoLocation.prototype.setCoordinatesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.nv.GeoLocation.Point=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nv.GeoLocation.Point}
 */
proto.nv.GeoLocation.prototype.addCoordinates = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.nv.GeoLocation.Point, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nv.GeoLocation} returns this
 */
proto.nv.GeoLocation.prototype.clearCoordinatesList = function() {
  return this.setCoordinatesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nv.Behavior.repeatedFields_ = [7,10,21,22,23,24];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nv.Behavior.prototype.toObject = function(opt_includeInstance) {
  return proto.nv.Behavior.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nv.Behavior} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nv.Behavior.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    end: (f = msg.getEnd()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    locations: (f = msg.getLocations()) && proto.nv.GeoLocation.toObject(includeInstance, f),
    smoothlocations: (f = msg.getSmoothlocations()) && proto.nv.GeoLocation.toObject(includeInstance, f),
    edgesList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    distance: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    speed: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0),
    speedovertimeList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 10)) == null ? undefined : f,
    timeinterval: jspb.Message.getFloatingPointFieldWithDefault(msg, 11, 0.0),
    bearing: jspb.Message.getFloatingPointFieldWithDefault(msg, 12, 0.0),
    direction: jspb.Message.getFieldWithDefault(msg, 13, ""),
    length: jspb.Message.getFieldWithDefault(msg, 14, 0),
    place: (f = msg.getPlace()) && schema_pb.Place.toObject(includeInstance, f),
    sensor: (f = msg.getSensor()) && schema_pb.Sensor.toObject(includeInstance, f),
    analyticsmodule: (f = msg.getAnalyticsmodule()) && schema_pb.AnalyticsModule.toObject(includeInstance, f),
    object: (f = msg.getObject()) && schema_pb.Object.toObject(includeInstance, f),
    event: (f = msg.getEvent()) && schema_pb.Event.toObject(includeInstance, f),
    videopath: jspb.Message.getFieldWithDefault(msg, 20, ""),
    posesList: jspb.Message.toObjectList(msg.getPosesList(),
    schema_pb.Pose.toObject, includeInstance),
    lipactivitiesList: jspb.Message.toObjectList(msg.getLipactivitiesList(),
    schema_pb.LipActivity.toObject, includeInstance),
    gazesList: jspb.Message.toObjectList(msg.getGazesList(),
    schema_pb.Gaze.toObject, includeInstance),
    embeddingsList: jspb.Message.toObjectList(msg.getEmbeddingsList(),
    schema_pb.Embedding.toObject, includeInstance),
    llm: (f = msg.getLlm()) && schema_pb.LLM.toObject(includeInstance, f),
    infoMap: (f = msg.getInfoMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nv.Behavior}
 */
proto.nv.Behavior.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nv.Behavior;
  return proto.nv.Behavior.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nv.Behavior} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nv.Behavior}
 */
proto.nv.Behavior.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEnd(value);
      break;
    case 5:
      var value = new proto.nv.GeoLocation;
      reader.readMessage(value,proto.nv.GeoLocation.deserializeBinaryFromReader);
      msg.setLocations(value);
      break;
    case 6:
      var value = new proto.nv.GeoLocation;
      reader.readMessage(value,proto.nv.GeoLocation.deserializeBinaryFromReader);
      msg.setSmoothlocations(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addEdges(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDistance(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSpeed(value);
      break;
    case 10:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addSpeedovertime(values[i]);
      }
      break;
    case 11:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTimeinterval(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setBearing(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setDirection(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLength(value);
      break;
    case 15:
      var value = new schema_pb.Place;
      reader.readMessage(value,schema_pb.Place.deserializeBinaryFromReader);
      msg.setPlace(value);
      break;
    case 16:
      var value = new schema_pb.Sensor;
      reader.readMessage(value,schema_pb.Sensor.deserializeBinaryFromReader);
      msg.setSensor(value);
      break;
    case 17:
      var value = new schema_pb.AnalyticsModule;
      reader.readMessage(value,schema_pb.AnalyticsModule.deserializeBinaryFromReader);
      msg.setAnalyticsmodule(value);
      break;
    case 18:
      var value = new schema_pb.Object;
      reader.readMessage(value,schema_pb.Object.deserializeBinaryFromReader);
      msg.setObject(value);
      break;
    case 19:
      var value = new schema_pb.Event;
      reader.readMessage(value,schema_pb.Event.deserializeBinaryFromReader);
      msg.setEvent(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setVideopath(value);
      break;
    case 21:
      var value = new schema_pb.Pose;
      reader.readMessage(value,schema_pb.Pose.deserializeBinaryFromReader);
      msg.addPoses(value);
      break;
    case 22:
      var value = new schema_pb.LipActivity;
      reader.readMessage(value,schema_pb.LipActivity.deserializeBinaryFromReader);
      msg.addLipactivities(value);
      break;
    case 23:
      var value = new schema_pb.Gaze;
      reader.readMessage(value,schema_pb.Gaze.deserializeBinaryFromReader);
      msg.addGazes(value);
      break;
    case 24:
      var value = new schema_pb.Embedding;
      reader.readMessage(value,schema_pb.Embedding.deserializeBinaryFromReader);
      msg.addEmbeddings(value);
      break;
    case 26:
      var value = new schema_pb.LLM;
      reader.readMessage(value,schema_pb.LLM.deserializeBinaryFromReader);
      msg.setLlm(value);
      break;
    case 25:
      var value = msg.getInfoMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nv.Behavior.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nv.Behavior.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nv.Behavior} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nv.Behavior.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEnd();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getLocations();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.nv.GeoLocation.serializeBinaryToWriter
    );
  }
  f = message.getSmoothlocations();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.nv.GeoLocation.serializeBinaryToWriter
    );
  }
  f = message.getEdgesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
  f = message.getDistance();
  if (f !== 0.0) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = message.getSpeed();
  if (f !== 0.0) {
    writer.writeDouble(
      9,
      f
    );
  }
  f = message.getSpeedovertimeList();
  if (f.length > 0) {
    writer.writePackedDouble(
      10,
      f
    );
  }
  f = message.getTimeinterval();
  if (f !== 0.0) {
    writer.writeDouble(
      11,
      f
    );
  }
  f = message.getBearing();
  if (f !== 0.0) {
    writer.writeDouble(
      12,
      f
    );
  }
  f = message.getDirection();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getLength();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getPlace();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      schema_pb.Place.serializeBinaryToWriter
    );
  }
  f = message.getSensor();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      schema_pb.Sensor.serializeBinaryToWriter
    );
  }
  f = message.getAnalyticsmodule();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      schema_pb.AnalyticsModule.serializeBinaryToWriter
    );
  }
  f = message.getObject();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      schema_pb.Object.serializeBinaryToWriter
    );
  }
  f = message.getEvent();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      schema_pb.Event.serializeBinaryToWriter
    );
  }
  f = message.getVideopath();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
  f = message.getPosesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      21,
      f,
      schema_pb.Pose.serializeBinaryToWriter
    );
  }
  f = message.getLipactivitiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      22,
      f,
      schema_pb.LipActivity.serializeBinaryToWriter
    );
  }
  f = message.getGazesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      23,
      f,
      schema_pb.Gaze.serializeBinaryToWriter
    );
  }
  f = message.getEmbeddingsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      24,
      f,
      schema_pb.Embedding.serializeBinaryToWriter
    );
  }
  f = message.getLlm();
  if (f != null) {
    writer.writeMessage(
      26,
      f,
      schema_pb.LLM.serializeBinaryToWriter
    );
  }
  f = message.getInfoMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(25, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.nv.Behavior.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.nv.Behavior.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.nv.Behavior} returns this
*/
proto.nv.Behavior.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nv.Behavior.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp end = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.nv.Behavior.prototype.getEnd = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.nv.Behavior} returns this
*/
proto.nv.Behavior.prototype.setEnd = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.clearEnd = function() {
  return this.setEnd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nv.Behavior.prototype.hasEnd = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional GeoLocation locations = 5;
 * @return {?proto.nv.GeoLocation}
 */
proto.nv.Behavior.prototype.getLocations = function() {
  return /** @type{?proto.nv.GeoLocation} */ (
    jspb.Message.getWrapperField(this, proto.nv.GeoLocation, 5));
};


/**
 * @param {?proto.nv.GeoLocation|undefined} value
 * @return {!proto.nv.Behavior} returns this
*/
proto.nv.Behavior.prototype.setLocations = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.clearLocations = function() {
  return this.setLocations(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nv.Behavior.prototype.hasLocations = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional GeoLocation smoothLocations = 6;
 * @return {?proto.nv.GeoLocation}
 */
proto.nv.Behavior.prototype.getSmoothlocations = function() {
  return /** @type{?proto.nv.GeoLocation} */ (
    jspb.Message.getWrapperField(this, proto.nv.GeoLocation, 6));
};


/**
 * @param {?proto.nv.GeoLocation|undefined} value
 * @return {!proto.nv.Behavior} returns this
*/
proto.nv.Behavior.prototype.setSmoothlocations = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.clearSmoothlocations = function() {
  return this.setSmoothlocations(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nv.Behavior.prototype.hasSmoothlocations = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated string edges = 7;
 * @return {!Array<string>}
 */
proto.nv.Behavior.prototype.getEdgesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.setEdgesList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.addEdges = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.clearEdgesList = function() {
  return this.setEdgesList([]);
};


/**
 * optional double distance = 8;
 * @return {number}
 */
proto.nv.Behavior.prototype.getDistance = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.setDistance = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional double speed = 9;
 * @return {number}
 */
proto.nv.Behavior.prototype.getSpeed = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.setSpeed = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * repeated double speedOverTime = 10;
 * @return {!Array<number>}
 */
proto.nv.Behavior.prototype.getSpeedovertimeList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 10));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.setSpeedovertimeList = function(value) {
  return jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.addSpeedovertime = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.clearSpeedovertimeList = function() {
  return this.setSpeedovertimeList([]);
};


/**
 * optional double timeInterval = 11;
 * @return {number}
 */
proto.nv.Behavior.prototype.getTimeinterval = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 11, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.setTimeinterval = function(value) {
  return jspb.Message.setProto3FloatField(this, 11, value);
};


/**
 * optional double bearing = 12;
 * @return {number}
 */
proto.nv.Behavior.prototype.getBearing = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 12, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.setBearing = function(value) {
  return jspb.Message.setProto3FloatField(this, 12, value);
};


/**
 * optional string direction = 13;
 * @return {string}
 */
proto.nv.Behavior.prototype.getDirection = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.setDirection = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional int32 length = 14;
 * @return {number}
 */
proto.nv.Behavior.prototype.getLength = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.setLength = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional Place place = 15;
 * @return {?proto.nv.Place}
 */
proto.nv.Behavior.prototype.getPlace = function() {
  return /** @type{?proto.nv.Place} */ (
    jspb.Message.getWrapperField(this, schema_pb.Place, 15));
};


/**
 * @param {?proto.nv.Place|undefined} value
 * @return {!proto.nv.Behavior} returns this
*/
proto.nv.Behavior.prototype.setPlace = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.clearPlace = function() {
  return this.setPlace(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nv.Behavior.prototype.hasPlace = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional Sensor sensor = 16;
 * @return {?proto.nv.Sensor}
 */
proto.nv.Behavior.prototype.getSensor = function() {
  return /** @type{?proto.nv.Sensor} */ (
    jspb.Message.getWrapperField(this, schema_pb.Sensor, 16));
};


/**
 * @param {?proto.nv.Sensor|undefined} value
 * @return {!proto.nv.Behavior} returns this
*/
proto.nv.Behavior.prototype.setSensor = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.clearSensor = function() {
  return this.setSensor(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nv.Behavior.prototype.hasSensor = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional AnalyticsModule analyticsModule = 17;
 * @return {?proto.nv.AnalyticsModule}
 */
proto.nv.Behavior.prototype.getAnalyticsmodule = function() {
  return /** @type{?proto.nv.AnalyticsModule} */ (
    jspb.Message.getWrapperField(this, schema_pb.AnalyticsModule, 17));
};


/**
 * @param {?proto.nv.AnalyticsModule|undefined} value
 * @return {!proto.nv.Behavior} returns this
*/
proto.nv.Behavior.prototype.setAnalyticsmodule = function(value) {
  return jspb.Message.setWrapperField(this, 17, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.clearAnalyticsmodule = function() {
  return this.setAnalyticsmodule(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nv.Behavior.prototype.hasAnalyticsmodule = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional Object object = 18;
 * @return {?proto.nv.Object}
 */
proto.nv.Behavior.prototype.getObject = function() {
  return /** @type{?proto.nv.Object} */ (
    jspb.Message.getWrapperField(this, schema_pb.Object, 18));
};


/**
 * @param {?proto.nv.Object|undefined} value
 * @return {!proto.nv.Behavior} returns this
*/
proto.nv.Behavior.prototype.setObject = function(value) {
  return jspb.Message.setWrapperField(this, 18, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.clearObject = function() {
  return this.setObject(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nv.Behavior.prototype.hasObject = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional Event event = 19;
 * @return {?proto.nv.Event}
 */
proto.nv.Behavior.prototype.getEvent = function() {
  return /** @type{?proto.nv.Event} */ (
    jspb.Message.getWrapperField(this, schema_pb.Event, 19));
};


/**
 * @param {?proto.nv.Event|undefined} value
 * @return {!proto.nv.Behavior} returns this
*/
proto.nv.Behavior.prototype.setEvent = function(value) {
  return jspb.Message.setWrapperField(this, 19, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.clearEvent = function() {
  return this.setEvent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nv.Behavior.prototype.hasEvent = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional string videoPath = 20;
 * @return {string}
 */
proto.nv.Behavior.prototype.getVideopath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/**
 * @param {string} value
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.setVideopath = function(value) {
  return jspb.Message.setProto3StringField(this, 20, value);
};


/**
 * repeated Pose poses = 21;
 * @return {!Array<!proto.nv.Pose>}
 */
proto.nv.Behavior.prototype.getPosesList = function() {
  return /** @type{!Array<!proto.nv.Pose>} */ (
    jspb.Message.getRepeatedWrapperField(this, schema_pb.Pose, 21));
};


/**
 * @param {!Array<!proto.nv.Pose>} value
 * @return {!proto.nv.Behavior} returns this
*/
proto.nv.Behavior.prototype.setPosesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 21, value);
};


/**
 * @param {!proto.nv.Pose=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nv.Pose}
 */
proto.nv.Behavior.prototype.addPoses = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 21, opt_value, proto.nv.Pose, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.clearPosesList = function() {
  return this.setPosesList([]);
};


/**
 * repeated LipActivity lipActivities = 22;
 * @return {!Array<!proto.nv.LipActivity>}
 */
proto.nv.Behavior.prototype.getLipactivitiesList = function() {
  return /** @type{!Array<!proto.nv.LipActivity>} */ (
    jspb.Message.getRepeatedWrapperField(this, schema_pb.LipActivity, 22));
};


/**
 * @param {!Array<!proto.nv.LipActivity>} value
 * @return {!proto.nv.Behavior} returns this
*/
proto.nv.Behavior.prototype.setLipactivitiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 22, value);
};


/**
 * @param {!proto.nv.LipActivity=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nv.LipActivity}
 */
proto.nv.Behavior.prototype.addLipactivities = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 22, opt_value, proto.nv.LipActivity, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.clearLipactivitiesList = function() {
  return this.setLipactivitiesList([]);
};


/**
 * repeated Gaze gazes = 23;
 * @return {!Array<!proto.nv.Gaze>}
 */
proto.nv.Behavior.prototype.getGazesList = function() {
  return /** @type{!Array<!proto.nv.Gaze>} */ (
    jspb.Message.getRepeatedWrapperField(this, schema_pb.Gaze, 23));
};


/**
 * @param {!Array<!proto.nv.Gaze>} value
 * @return {!proto.nv.Behavior} returns this
*/
proto.nv.Behavior.prototype.setGazesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 23, value);
};


/**
 * @param {!proto.nv.Gaze=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nv.Gaze}
 */
proto.nv.Behavior.prototype.addGazes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 23, opt_value, proto.nv.Gaze, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.clearGazesList = function() {
  return this.setGazesList([]);
};


/**
 * repeated Embedding embeddings = 24;
 * @return {!Array<!proto.nv.Embedding>}
 */
proto.nv.Behavior.prototype.getEmbeddingsList = function() {
  return /** @type{!Array<!proto.nv.Embedding>} */ (
    jspb.Message.getRepeatedWrapperField(this, schema_pb.Embedding, 24));
};


/**
 * @param {!Array<!proto.nv.Embedding>} value
 * @return {!proto.nv.Behavior} returns this
*/
proto.nv.Behavior.prototype.setEmbeddingsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 24, value);
};


/**
 * @param {!proto.nv.Embedding=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nv.Embedding}
 */
proto.nv.Behavior.prototype.addEmbeddings = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 24, opt_value, proto.nv.Embedding, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.clearEmbeddingsList = function() {
  return this.setEmbeddingsList([]);
};


/**
 * optional LLM llm = 26;
 * @return {?proto.nv.LLM}
 */
proto.nv.Behavior.prototype.getLlm = function() {
  return /** @type{?proto.nv.LLM} */ (
    jspb.Message.getWrapperField(this, schema_pb.LLM, 26));
};


/**
 * @param {?proto.nv.LLM|undefined} value
 * @return {!proto.nv.Behavior} returns this
*/
proto.nv.Behavior.prototype.setLlm = function(value) {
  return jspb.Message.setWrapperField(this, 26, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.clearLlm = function() {
  return this.setLlm(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nv.Behavior.prototype.hasLlm = function() {
  return jspb.Message.getField(this, 26) != null;
};


/**
 * map<string, string> info = 25;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.nv.Behavior.prototype.getInfoMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 25, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.nv.Behavior} returns this
 */
proto.nv.Behavior.prototype.clearInfoMap = function() {
  this.getInfoMap().clear();
  return this;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nv.Incident.repeatedFields_ = [4,5,9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nv.Incident.prototype.toObject = function(opt_includeInstance) {
  return proto.nv.Incident.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nv.Incident} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nv.Incident.toObject = function(includeInstance, msg) {
  var f, obj = {
    sensorid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    end: (f = msg.getEnd()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    objectidsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    frameidsList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    place: (f = msg.getPlace()) && schema_pb.Place.toObject(includeInstance, f),
    analyticsmodule: (f = msg.getAnalyticsmodule()) && schema_pb.AnalyticsModule.toObject(includeInstance, f),
    category: jspb.Message.getFieldWithDefault(msg, 8, ""),
    embeddingsList: jspb.Message.toObjectList(msg.getEmbeddingsList(),
    schema_pb.Embedding.toObject, includeInstance),
    isanomaly: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    llm: (f = msg.getLlm()) && schema_pb.LLM.toObject(includeInstance, f),
    infoMap: (f = msg.getInfoMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nv.Incident}
 */
proto.nv.Incident.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nv.Incident;
  return proto.nv.Incident.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nv.Incident} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nv.Incident}
 */
proto.nv.Incident.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSensorid(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEnd(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addObjectids(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addFrameids(value);
      break;
    case 6:
      var value = new schema_pb.Place;
      reader.readMessage(value,schema_pb.Place.deserializeBinaryFromReader);
      msg.setPlace(value);
      break;
    case 7:
      var value = new schema_pb.AnalyticsModule;
      reader.readMessage(value,schema_pb.AnalyticsModule.deserializeBinaryFromReader);
      msg.setAnalyticsmodule(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategory(value);
      break;
    case 9:
      var value = new schema_pb.Embedding;
      reader.readMessage(value,schema_pb.Embedding.deserializeBinaryFromReader);
      msg.addEmbeddings(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsanomaly(value);
      break;
    case 12:
      var value = new schema_pb.LLM;
      reader.readMessage(value,schema_pb.LLM.deserializeBinaryFromReader);
      msg.setLlm(value);
      break;
    case 11:
      var value = msg.getInfoMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nv.Incident.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nv.Incident.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nv.Incident} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nv.Incident.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSensorid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEnd();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getObjectidsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
  f = message.getFrameidsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = message.getPlace();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      schema_pb.Place.serializeBinaryToWriter
    );
  }
  f = message.getAnalyticsmodule();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      schema_pb.AnalyticsModule.serializeBinaryToWriter
    );
  }
  f = message.getCategory();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getEmbeddingsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      schema_pb.Embedding.serializeBinaryToWriter
    );
  }
  f = message.getIsanomaly();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getLlm();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      schema_pb.LLM.serializeBinaryToWriter
    );
  }
  f = message.getInfoMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(11, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string sensorId = 1;
 * @return {string}
 */
proto.nv.Incident.prototype.getSensorid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.nv.Incident} returns this
 */
proto.nv.Incident.prototype.setSensorid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.nv.Incident.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.nv.Incident} returns this
*/
proto.nv.Incident.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nv.Incident} returns this
 */
proto.nv.Incident.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nv.Incident.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp end = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.nv.Incident.prototype.getEnd = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.nv.Incident} returns this
*/
proto.nv.Incident.prototype.setEnd = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nv.Incident} returns this
 */
proto.nv.Incident.prototype.clearEnd = function() {
  return this.setEnd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nv.Incident.prototype.hasEnd = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated string objectIds = 4;
 * @return {!Array<string>}
 */
proto.nv.Incident.prototype.getObjectidsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.nv.Incident} returns this
 */
proto.nv.Incident.prototype.setObjectidsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.nv.Incident} returns this
 */
proto.nv.Incident.prototype.addObjectids = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nv.Incident} returns this
 */
proto.nv.Incident.prototype.clearObjectidsList = function() {
  return this.setObjectidsList([]);
};


/**
 * repeated string frameIds = 5;
 * @return {!Array<string>}
 */
proto.nv.Incident.prototype.getFrameidsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.nv.Incident} returns this
 */
proto.nv.Incident.prototype.setFrameidsList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.nv.Incident} returns this
 */
proto.nv.Incident.prototype.addFrameids = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nv.Incident} returns this
 */
proto.nv.Incident.prototype.clearFrameidsList = function() {
  return this.setFrameidsList([]);
};


/**
 * optional Place place = 6;
 * @return {?proto.nv.Place}
 */
proto.nv.Incident.prototype.getPlace = function() {
  return /** @type{?proto.nv.Place} */ (
    jspb.Message.getWrapperField(this, schema_pb.Place, 6));
};


/**
 * @param {?proto.nv.Place|undefined} value
 * @return {!proto.nv.Incident} returns this
*/
proto.nv.Incident.prototype.setPlace = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nv.Incident} returns this
 */
proto.nv.Incident.prototype.clearPlace = function() {
  return this.setPlace(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nv.Incident.prototype.hasPlace = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional AnalyticsModule analyticsModule = 7;
 * @return {?proto.nv.AnalyticsModule}
 */
proto.nv.Incident.prototype.getAnalyticsmodule = function() {
  return /** @type{?proto.nv.AnalyticsModule} */ (
    jspb.Message.getWrapperField(this, schema_pb.AnalyticsModule, 7));
};


/**
 * @param {?proto.nv.AnalyticsModule|undefined} value
 * @return {!proto.nv.Incident} returns this
*/
proto.nv.Incident.prototype.setAnalyticsmodule = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nv.Incident} returns this
 */
proto.nv.Incident.prototype.clearAnalyticsmodule = function() {
  return this.setAnalyticsmodule(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nv.Incident.prototype.hasAnalyticsmodule = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string category = 8;
 * @return {string}
 */
proto.nv.Incident.prototype.getCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.nv.Incident} returns this
 */
proto.nv.Incident.prototype.setCategory = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * repeated Embedding embeddings = 9;
 * @return {!Array<!proto.nv.Embedding>}
 */
proto.nv.Incident.prototype.getEmbeddingsList = function() {
  return /** @type{!Array<!proto.nv.Embedding>} */ (
    jspb.Message.getRepeatedWrapperField(this, schema_pb.Embedding, 9));
};


/**
 * @param {!Array<!proto.nv.Embedding>} value
 * @return {!proto.nv.Incident} returns this
*/
proto.nv.Incident.prototype.setEmbeddingsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.nv.Embedding=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nv.Embedding}
 */
proto.nv.Incident.prototype.addEmbeddings = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.nv.Embedding, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nv.Incident} returns this
 */
proto.nv.Incident.prototype.clearEmbeddingsList = function() {
  return this.setEmbeddingsList([]);
};


/**
 * optional bool isAnomaly = 10;
 * @return {boolean}
 */
proto.nv.Incident.prototype.getIsanomaly = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.nv.Incident} returns this
 */
proto.nv.Incident.prototype.setIsanomaly = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional LLM llm = 12;
 * @return {?proto.nv.LLM}
 */
proto.nv.Incident.prototype.getLlm = function() {
  return /** @type{?proto.nv.LLM} */ (
    jspb.Message.getWrapperField(this, schema_pb.LLM, 12));
};


/**
 * @param {?proto.nv.LLM|undefined} value
 * @return {!proto.nv.Incident} returns this
*/
proto.nv.Incident.prototype.setLlm = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nv.Incident} returns this
 */
proto.nv.Incident.prototype.clearLlm = function() {
  return this.setLlm(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nv.Incident.prototype.hasLlm = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * map<string, string> info = 11;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.nv.Incident.prototype.getInfoMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 11, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.nv.Incident} returns this
 */
proto.nv.Incident.prototype.clearInfoMap = function() {
  this.getInfoMap().clear();
  return this;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nv.SpaceUtilizationMetrics.prototype.toObject = function(opt_includeInstance) {
  return proto.nv.SpaceUtilizationMetrics.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nv.SpaceUtilizationMetrics} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nv.SpaceUtilizationMetrics.toObject = function(includeInstance, msg) {
  var f, obj = {
    spaceoccupied: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    freespace: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    totalspace: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    spaceutilization: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    numextrapallets: jspb.Message.getFieldWithDefault(msg, 5, 0),
    utilizablefreespace: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    freespacequality: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    isunsafe: jspb.Message.getBooleanFieldWithDefault(msg, 8, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nv.SpaceUtilizationMetrics}
 */
proto.nv.SpaceUtilizationMetrics.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nv.SpaceUtilizationMetrics;
  return proto.nv.SpaceUtilizationMetrics.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nv.SpaceUtilizationMetrics} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nv.SpaceUtilizationMetrics}
 */
proto.nv.SpaceUtilizationMetrics.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSpaceoccupied(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setFreespace(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTotalspace(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSpaceutilization(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNumextrapallets(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setUtilizablefreespace(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setFreespacequality(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsunsafe(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nv.SpaceUtilizationMetrics.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nv.SpaceUtilizationMetrics.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nv.SpaceUtilizationMetrics} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nv.SpaceUtilizationMetrics.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpaceoccupied();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getFreespace();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getTotalspace();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getSpaceutilization();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getNumextrapallets();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getUtilizablefreespace();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getFreespacequality();
  if (f !== 0.0) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = message.getIsunsafe();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
};


/**
 * optional double spaceOccupied = 1;
 * @return {number}
 */
proto.nv.SpaceUtilizationMetrics.prototype.getSpaceoccupied = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.nv.SpaceUtilizationMetrics} returns this
 */
proto.nv.SpaceUtilizationMetrics.prototype.setSpaceoccupied = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double freeSpace = 2;
 * @return {number}
 */
proto.nv.SpaceUtilizationMetrics.prototype.getFreespace = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.nv.SpaceUtilizationMetrics} returns this
 */
proto.nv.SpaceUtilizationMetrics.prototype.setFreespace = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double totalSpace = 3;
 * @return {number}
 */
proto.nv.SpaceUtilizationMetrics.prototype.getTotalspace = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.nv.SpaceUtilizationMetrics} returns this
 */
proto.nv.SpaceUtilizationMetrics.prototype.setTotalspace = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double spaceUtilization = 4;
 * @return {number}
 */
proto.nv.SpaceUtilizationMetrics.prototype.getSpaceutilization = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.nv.SpaceUtilizationMetrics} returns this
 */
proto.nv.SpaceUtilizationMetrics.prototype.setSpaceutilization = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional int32 numExtraPallets = 5;
 * @return {number}
 */
proto.nv.SpaceUtilizationMetrics.prototype.getNumextrapallets = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.nv.SpaceUtilizationMetrics} returns this
 */
proto.nv.SpaceUtilizationMetrics.prototype.setNumextrapallets = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional double utilizableFreeSpace = 6;
 * @return {number}
 */
proto.nv.SpaceUtilizationMetrics.prototype.getUtilizablefreespace = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.nv.SpaceUtilizationMetrics} returns this
 */
proto.nv.SpaceUtilizationMetrics.prototype.setUtilizablefreespace = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional double freeSpaceQuality = 7;
 * @return {number}
 */
proto.nv.SpaceUtilizationMetrics.prototype.getFreespacequality = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.nv.SpaceUtilizationMetrics} returns this
 */
proto.nv.SpaceUtilizationMetrics.prototype.setFreespacequality = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional bool isUnsafe = 8;
 * @return {boolean}
 */
proto.nv.SpaceUtilizationMetrics.prototype.getIsunsafe = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.nv.SpaceUtilizationMetrics} returns this
 */
proto.nv.SpaceUtilizationMetrics.prototype.setIsunsafe = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nv.SpaceUtilizationLayouts.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nv.SpaceUtilizationLayouts.prototype.toObject = function(opt_includeInstance) {
  return proto.nv.SpaceUtilizationLayouts.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nv.SpaceUtilizationLayouts} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nv.SpaceUtilizationLayouts.toObject = function(includeInstance, msg) {
  var f, obj = {
    freespaceList: jspb.Message.toObjectList(msg.getFreespaceList(),
    schema_pb.Polygon.toObject, includeInstance),
    utilizablefreespaceList: jspb.Message.toObjectList(msg.getUtilizablefreespaceList(),
    schema_pb.Polygon.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nv.SpaceUtilizationLayouts}
 */
proto.nv.SpaceUtilizationLayouts.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nv.SpaceUtilizationLayouts;
  return proto.nv.SpaceUtilizationLayouts.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nv.SpaceUtilizationLayouts} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nv.SpaceUtilizationLayouts}
 */
proto.nv.SpaceUtilizationLayouts.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new schema_pb.Polygon;
      reader.readMessage(value,schema_pb.Polygon.deserializeBinaryFromReader);
      msg.addFreespace(value);
      break;
    case 2:
      var value = new schema_pb.Polygon;
      reader.readMessage(value,schema_pb.Polygon.deserializeBinaryFromReader);
      msg.addUtilizablefreespace(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nv.SpaceUtilizationLayouts.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nv.SpaceUtilizationLayouts.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nv.SpaceUtilizationLayouts} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nv.SpaceUtilizationLayouts.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFreespaceList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      schema_pb.Polygon.serializeBinaryToWriter
    );
  }
  f = message.getUtilizablefreespaceList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      schema_pb.Polygon.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Polygon freeSpace = 1;
 * @return {!Array<!proto.nv.Polygon>}
 */
proto.nv.SpaceUtilizationLayouts.prototype.getFreespaceList = function() {
  return /** @type{!Array<!proto.nv.Polygon>} */ (
    jspb.Message.getRepeatedWrapperField(this, schema_pb.Polygon, 1));
};


/**
 * @param {!Array<!proto.nv.Polygon>} value
 * @return {!proto.nv.SpaceUtilizationLayouts} returns this
*/
proto.nv.SpaceUtilizationLayouts.prototype.setFreespaceList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.nv.Polygon=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nv.Polygon}
 */
proto.nv.SpaceUtilizationLayouts.prototype.addFreespace = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.nv.Polygon, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nv.SpaceUtilizationLayouts} returns this
 */
proto.nv.SpaceUtilizationLayouts.prototype.clearFreespaceList = function() {
  return this.setFreespaceList([]);
};


/**
 * repeated Polygon utilizableFreeSpace = 2;
 * @return {!Array<!proto.nv.Polygon>}
 */
proto.nv.SpaceUtilizationLayouts.prototype.getUtilizablefreespaceList = function() {
  return /** @type{!Array<!proto.nv.Polygon>} */ (
    jspb.Message.getRepeatedWrapperField(this, schema_pb.Polygon, 2));
};


/**
 * @param {!Array<!proto.nv.Polygon>} value
 * @return {!proto.nv.SpaceUtilizationLayouts} returns this
*/
proto.nv.SpaceUtilizationLayouts.prototype.setUtilizablefreespaceList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.nv.Polygon=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nv.Polygon}
 */
proto.nv.SpaceUtilizationLayouts.prototype.addUtilizablefreespace = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.nv.Polygon, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nv.SpaceUtilizationLayouts} returns this
 */
proto.nv.SpaceUtilizationLayouts.prototype.clearUtilizablefreespaceList = function() {
  return this.setUtilizablefreespaceList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nv.SpaceUtilization.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nv.SpaceUtilization.prototype.toObject = function(opt_includeInstance) {
  return proto.nv.SpaceUtilization.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nv.SpaceUtilization} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nv.SpaceUtilization.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    metrics: (f = msg.getMetrics()) && proto.nv.SpaceUtilizationMetrics.toObject(includeInstance, f),
    sensorsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    layouts: (f = msg.getLayouts()) && proto.nv.SpaceUtilizationLayouts.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nv.SpaceUtilization}
 */
proto.nv.SpaceUtilization.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nv.SpaceUtilization;
  return proto.nv.SpaceUtilization.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nv.SpaceUtilization} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nv.SpaceUtilization}
 */
proto.nv.SpaceUtilization.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 3:
      var value = new proto.nv.SpaceUtilizationMetrics;
      reader.readMessage(value,proto.nv.SpaceUtilizationMetrics.deserializeBinaryFromReader);
      msg.setMetrics(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addSensors(value);
      break;
    case 5:
      var value = new proto.nv.SpaceUtilizationLayouts;
      reader.readMessage(value,proto.nv.SpaceUtilizationLayouts.deserializeBinaryFromReader);
      msg.setLayouts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nv.SpaceUtilization.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nv.SpaceUtilization.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nv.SpaceUtilization} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nv.SpaceUtilization.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getMetrics();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.nv.SpaceUtilizationMetrics.serializeBinaryToWriter
    );
  }
  f = message.getSensorsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
  f = message.getLayouts();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.nv.SpaceUtilizationLayouts.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.nv.SpaceUtilization.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.nv.SpaceUtilization} returns this
 */
proto.nv.SpaceUtilization.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.nv.SpaceUtilization.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.nv.SpaceUtilization} returns this
*/
proto.nv.SpaceUtilization.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nv.SpaceUtilization} returns this
 */
proto.nv.SpaceUtilization.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nv.SpaceUtilization.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional SpaceUtilizationMetrics metrics = 3;
 * @return {?proto.nv.SpaceUtilizationMetrics}
 */
proto.nv.SpaceUtilization.prototype.getMetrics = function() {
  return /** @type{?proto.nv.SpaceUtilizationMetrics} */ (
    jspb.Message.getWrapperField(this, proto.nv.SpaceUtilizationMetrics, 3));
};


/**
 * @param {?proto.nv.SpaceUtilizationMetrics|undefined} value
 * @return {!proto.nv.SpaceUtilization} returns this
*/
proto.nv.SpaceUtilization.prototype.setMetrics = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nv.SpaceUtilization} returns this
 */
proto.nv.SpaceUtilization.prototype.clearMetrics = function() {
  return this.setMetrics(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nv.SpaceUtilization.prototype.hasMetrics = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated string sensors = 4;
 * @return {!Array<string>}
 */
proto.nv.SpaceUtilization.prototype.getSensorsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.nv.SpaceUtilization} returns this
 */
proto.nv.SpaceUtilization.prototype.setSensorsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.nv.SpaceUtilization} returns this
 */
proto.nv.SpaceUtilization.prototype.addSensors = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nv.SpaceUtilization} returns this
 */
proto.nv.SpaceUtilization.prototype.clearSensorsList = function() {
  return this.setSensorsList([]);
};


/**
 * optional SpaceUtilizationLayouts layouts = 5;
 * @return {?proto.nv.SpaceUtilizationLayouts}
 */
proto.nv.SpaceUtilization.prototype.getLayouts = function() {
  return /** @type{?proto.nv.SpaceUtilizationLayouts} */ (
    jspb.Message.getWrapperField(this, proto.nv.SpaceUtilizationLayouts, 5));
};


/**
 * @param {?proto.nv.SpaceUtilizationLayouts|undefined} value
 * @return {!proto.nv.SpaceUtilization} returns this
*/
proto.nv.SpaceUtilization.prototype.setLayouts = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nv.SpaceUtilization} returns this
 */
proto.nv.SpaceUtilization.prototype.clearLayouts = function() {
  return this.setLayouts(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nv.SpaceUtilization.prototype.hasLayouts = function() {
  return jspb.Message.getField(this, 5) != null;
};


goog.object.extend(exports, proto.nv);
