// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/collector/metrics/v1/metrics_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_opentelemetry_2fproto_2fcollector_2fmetrics_2fv1_2fmetrics_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_opentelemetry_2fproto_2fcollector_2fmetrics_2fv1_2fmetrics_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "opentelemetry/proto/metrics/v1/metrics.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_opentelemetry_2fproto_2fcollector_2fmetrics_2fv1_2fmetrics_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_opentelemetry_2fproto_2fcollector_2fmetrics_2fv1_2fmetrics_5fservice_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_opentelemetry_2fproto_2fcollector_2fmetrics_2fv1_2fmetrics_5fservice_2eproto;
namespace opentelemetry {
namespace proto {
namespace collector {
namespace metrics {
namespace v1 {
class ExportMetricsPartialSuccess;
class ExportMetricsPartialSuccessDefaultTypeInternal;
extern ExportMetricsPartialSuccessDefaultTypeInternal _ExportMetricsPartialSuccess_default_instance_;
class ExportMetricsServiceRequest;
class ExportMetricsServiceRequestDefaultTypeInternal;
extern ExportMetricsServiceRequestDefaultTypeInternal _ExportMetricsServiceRequest_default_instance_;
class ExportMetricsServiceResponse;
class ExportMetricsServiceResponseDefaultTypeInternal;
extern ExportMetricsServiceResponseDefaultTypeInternal _ExportMetricsServiceResponse_default_instance_;
}  // namespace v1
}  // namespace metrics
}  // namespace collector
}  // namespace proto
}  // namespace opentelemetry
PROTOBUF_NAMESPACE_OPEN
template<> ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess* Arena::CreateMaybeMessage<::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess>(Arena*);
template<> ::opentelemetry::proto::collector::metrics::v1::ExportMetricsServiceRequest* Arena::CreateMaybeMessage<::opentelemetry::proto::collector::metrics::v1::ExportMetricsServiceRequest>(Arena*);
template<> ::opentelemetry::proto::collector::metrics::v1::ExportMetricsServiceResponse* Arena::CreateMaybeMessage<::opentelemetry::proto::collector::metrics::v1::ExportMetricsServiceResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace opentelemetry {
namespace proto {
namespace collector {
namespace metrics {
namespace v1 {

// ===================================================================

class ExportMetricsServiceRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceRequest) */ {
 public:
  inline ExportMetricsServiceRequest() : ExportMetricsServiceRequest(nullptr) {};
  virtual ~ExportMetricsServiceRequest();

  ExportMetricsServiceRequest(const ExportMetricsServiceRequest& from);
  ExportMetricsServiceRequest(ExportMetricsServiceRequest&& from) noexcept
    : ExportMetricsServiceRequest() {
    *this = ::std::move(from);
  }

  inline ExportMetricsServiceRequest& operator=(const ExportMetricsServiceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExportMetricsServiceRequest& operator=(ExportMetricsServiceRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ExportMetricsServiceRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ExportMetricsServiceRequest* internal_default_instance() {
    return reinterpret_cast<const ExportMetricsServiceRequest*>(
               &_ExportMetricsServiceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ExportMetricsServiceRequest& a, ExportMetricsServiceRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ExportMetricsServiceRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExportMetricsServiceRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ExportMetricsServiceRequest* New() const final {
    return CreateMaybeMessage<ExportMetricsServiceRequest>(nullptr);
  }

  ExportMetricsServiceRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ExportMetricsServiceRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ExportMetricsServiceRequest& from);
  void MergeFrom(const ExportMetricsServiceRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ExportMetricsServiceRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceRequest";
  }
  protected:
  explicit ExportMetricsServiceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_opentelemetry_2fproto_2fcollector_2fmetrics_2fv1_2fmetrics_5fservice_2eproto);
    return ::descriptor_table_opentelemetry_2fproto_2fcollector_2fmetrics_2fv1_2fmetrics_5fservice_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResourceMetricsFieldNumber = 1,
  };
  // repeated .opentelemetry.proto.metrics.v1.ResourceMetrics resource_metrics = 1;
  int resource_metrics_size() const;
  private:
  int _internal_resource_metrics_size() const;
  public:
  void clear_resource_metrics();
  ::opentelemetry::proto::metrics::v1::ResourceMetrics* mutable_resource_metrics(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::metrics::v1::ResourceMetrics >*
      mutable_resource_metrics();
  private:
  const ::opentelemetry::proto::metrics::v1::ResourceMetrics& _internal_resource_metrics(int index) const;
  ::opentelemetry::proto::metrics::v1::ResourceMetrics* _internal_add_resource_metrics();
  public:
  const ::opentelemetry::proto::metrics::v1::ResourceMetrics& resource_metrics(int index) const;
  ::opentelemetry::proto::metrics::v1::ResourceMetrics* add_resource_metrics();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::metrics::v1::ResourceMetrics >&
      resource_metrics() const;

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::metrics::v1::ResourceMetrics > resource_metrics_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_opentelemetry_2fproto_2fcollector_2fmetrics_2fv1_2fmetrics_5fservice_2eproto;
};
// -------------------------------------------------------------------

class ExportMetricsServiceResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceResponse) */ {
 public:
  inline ExportMetricsServiceResponse() : ExportMetricsServiceResponse(nullptr) {};
  virtual ~ExportMetricsServiceResponse();

  ExportMetricsServiceResponse(const ExportMetricsServiceResponse& from);
  ExportMetricsServiceResponse(ExportMetricsServiceResponse&& from) noexcept
    : ExportMetricsServiceResponse() {
    *this = ::std::move(from);
  }

  inline ExportMetricsServiceResponse& operator=(const ExportMetricsServiceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExportMetricsServiceResponse& operator=(ExportMetricsServiceResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ExportMetricsServiceResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ExportMetricsServiceResponse* internal_default_instance() {
    return reinterpret_cast<const ExportMetricsServiceResponse*>(
               &_ExportMetricsServiceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ExportMetricsServiceResponse& a, ExportMetricsServiceResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ExportMetricsServiceResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExportMetricsServiceResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ExportMetricsServiceResponse* New() const final {
    return CreateMaybeMessage<ExportMetricsServiceResponse>(nullptr);
  }

  ExportMetricsServiceResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ExportMetricsServiceResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ExportMetricsServiceResponse& from);
  void MergeFrom(const ExportMetricsServiceResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ExportMetricsServiceResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceResponse";
  }
  protected:
  explicit ExportMetricsServiceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_opentelemetry_2fproto_2fcollector_2fmetrics_2fv1_2fmetrics_5fservice_2eproto);
    return ::descriptor_table_opentelemetry_2fproto_2fcollector_2fmetrics_2fv1_2fmetrics_5fservice_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPartialSuccessFieldNumber = 1,
  };
  // .opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess partial_success = 1;
  bool has_partial_success() const;
  private:
  bool _internal_has_partial_success() const;
  public:
  void clear_partial_success();
  const ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess& partial_success() const;
  ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess* release_partial_success();
  ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess* mutable_partial_success();
  void set_allocated_partial_success(::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess* partial_success);
  private:
  const ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess& _internal_partial_success() const;
  ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess* _internal_mutable_partial_success();
  public:
  void unsafe_arena_set_allocated_partial_success(
      ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess* partial_success);
  ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess* unsafe_arena_release_partial_success();

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess* partial_success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_opentelemetry_2fproto_2fcollector_2fmetrics_2fv1_2fmetrics_5fservice_2eproto;
};
// -------------------------------------------------------------------

class ExportMetricsPartialSuccess PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess) */ {
 public:
  inline ExportMetricsPartialSuccess() : ExportMetricsPartialSuccess(nullptr) {};
  virtual ~ExportMetricsPartialSuccess();

  ExportMetricsPartialSuccess(const ExportMetricsPartialSuccess& from);
  ExportMetricsPartialSuccess(ExportMetricsPartialSuccess&& from) noexcept
    : ExportMetricsPartialSuccess() {
    *this = ::std::move(from);
  }

  inline ExportMetricsPartialSuccess& operator=(const ExportMetricsPartialSuccess& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExportMetricsPartialSuccess& operator=(ExportMetricsPartialSuccess&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ExportMetricsPartialSuccess& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ExportMetricsPartialSuccess* internal_default_instance() {
    return reinterpret_cast<const ExportMetricsPartialSuccess*>(
               &_ExportMetricsPartialSuccess_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ExportMetricsPartialSuccess& a, ExportMetricsPartialSuccess& b) {
    a.Swap(&b);
  }
  inline void Swap(ExportMetricsPartialSuccess* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExportMetricsPartialSuccess* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ExportMetricsPartialSuccess* New() const final {
    return CreateMaybeMessage<ExportMetricsPartialSuccess>(nullptr);
  }

  ExportMetricsPartialSuccess* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ExportMetricsPartialSuccess>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ExportMetricsPartialSuccess& from);
  void MergeFrom(const ExportMetricsPartialSuccess& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ExportMetricsPartialSuccess* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess";
  }
  protected:
  explicit ExportMetricsPartialSuccess(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_opentelemetry_2fproto_2fcollector_2fmetrics_2fv1_2fmetrics_5fservice_2eproto);
    return ::descriptor_table_opentelemetry_2fproto_2fcollector_2fmetrics_2fv1_2fmetrics_5fservice_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorMessageFieldNumber = 2,
    kRejectedDataPointsFieldNumber = 1,
  };
  // string error_message = 2;
  void clear_error_message();
  const std::string& error_message() const;
  void set_error_message(const std::string& value);
  void set_error_message(std::string&& value);
  void set_error_message(const char* value);
  void set_error_message(const char* value, size_t size);
  std::string* mutable_error_message();
  std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_error_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_error_message(
      std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // int64 rejected_data_points = 1;
  void clear_rejected_data_points();
  ::PROTOBUF_NAMESPACE_ID::int64 rejected_data_points() const;
  void set_rejected_data_points(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_rejected_data_points() const;
  void _internal_set_rejected_data_points(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
  ::PROTOBUF_NAMESPACE_ID::int64 rejected_data_points_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_opentelemetry_2fproto_2fcollector_2fmetrics_2fv1_2fmetrics_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ExportMetricsServiceRequest

// repeated .opentelemetry.proto.metrics.v1.ResourceMetrics resource_metrics = 1;
inline int ExportMetricsServiceRequest::_internal_resource_metrics_size() const {
  return resource_metrics_.size();
}
inline int ExportMetricsServiceRequest::resource_metrics_size() const {
  return _internal_resource_metrics_size();
}
inline ::opentelemetry::proto::metrics::v1::ResourceMetrics* ExportMetricsServiceRequest::mutable_resource_metrics(int index) {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceRequest.resource_metrics)
  return resource_metrics_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::metrics::v1::ResourceMetrics >*
ExportMetricsServiceRequest::mutable_resource_metrics() {
  // @@protoc_insertion_point(field_mutable_list:opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceRequest.resource_metrics)
  return &resource_metrics_;
}
inline const ::opentelemetry::proto::metrics::v1::ResourceMetrics& ExportMetricsServiceRequest::_internal_resource_metrics(int index) const {
  return resource_metrics_.Get(index);
}
inline const ::opentelemetry::proto::metrics::v1::ResourceMetrics& ExportMetricsServiceRequest::resource_metrics(int index) const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceRequest.resource_metrics)
  return _internal_resource_metrics(index);
}
inline ::opentelemetry::proto::metrics::v1::ResourceMetrics* ExportMetricsServiceRequest::_internal_add_resource_metrics() {
  return resource_metrics_.Add();
}
inline ::opentelemetry::proto::metrics::v1::ResourceMetrics* ExportMetricsServiceRequest::add_resource_metrics() {
  // @@protoc_insertion_point(field_add:opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceRequest.resource_metrics)
  return _internal_add_resource_metrics();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::metrics::v1::ResourceMetrics >&
ExportMetricsServiceRequest::resource_metrics() const {
  // @@protoc_insertion_point(field_list:opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceRequest.resource_metrics)
  return resource_metrics_;
}

// -------------------------------------------------------------------

// ExportMetricsServiceResponse

// .opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess partial_success = 1;
inline bool ExportMetricsServiceResponse::_internal_has_partial_success() const {
  return this != internal_default_instance() && partial_success_ != nullptr;
}
inline bool ExportMetricsServiceResponse::has_partial_success() const {
  return _internal_has_partial_success();
}
inline void ExportMetricsServiceResponse::clear_partial_success() {
  if (GetArena() == nullptr && partial_success_ != nullptr) {
    delete partial_success_;
  }
  partial_success_ = nullptr;
}
inline const ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess& ExportMetricsServiceResponse::_internal_partial_success() const {
  const ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess* p = partial_success_;
  return p != nullptr ? *p : *reinterpret_cast<const ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess*>(
      &::opentelemetry::proto::collector::metrics::v1::_ExportMetricsPartialSuccess_default_instance_);
}
inline const ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess& ExportMetricsServiceResponse::partial_success() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceResponse.partial_success)
  return _internal_partial_success();
}
inline void ExportMetricsServiceResponse::unsafe_arena_set_allocated_partial_success(
    ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess* partial_success) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(partial_success_);
  }
  partial_success_ = partial_success;
  if (partial_success) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceResponse.partial_success)
}
inline ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess* ExportMetricsServiceResponse::release_partial_success() {
  auto temp = unsafe_arena_release_partial_success();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess* ExportMetricsServiceResponse::unsafe_arena_release_partial_success() {
  // @@protoc_insertion_point(field_release:opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceResponse.partial_success)
  
  ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess* temp = partial_success_;
  partial_success_ = nullptr;
  return temp;
}
inline ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess* ExportMetricsServiceResponse::_internal_mutable_partial_success() {
  
  if (partial_success_ == nullptr) {
    auto* p = CreateMaybeMessage<::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess>(GetArena());
    partial_success_ = p;
  }
  return partial_success_;
}
inline ::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess* ExportMetricsServiceResponse::mutable_partial_success() {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceResponse.partial_success)
  return _internal_mutable_partial_success();
}
inline void ExportMetricsServiceResponse::set_allocated_partial_success(::opentelemetry::proto::collector::metrics::v1::ExportMetricsPartialSuccess* partial_success) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete partial_success_;
  }
  if (partial_success) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(partial_success);
    if (message_arena != submessage_arena) {
      partial_success = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, partial_success, submessage_arena);
    }
    
  } else {
    
  }
  partial_success_ = partial_success;
  // @@protoc_insertion_point(field_set_allocated:opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceResponse.partial_success)
}

// -------------------------------------------------------------------

// ExportMetricsPartialSuccess

// int64 rejected_data_points = 1;
inline void ExportMetricsPartialSuccess::clear_rejected_data_points() {
  rejected_data_points_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ExportMetricsPartialSuccess::_internal_rejected_data_points() const {
  return rejected_data_points_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ExportMetricsPartialSuccess::rejected_data_points() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess.rejected_data_points)
  return _internal_rejected_data_points();
}
inline void ExportMetricsPartialSuccess::_internal_set_rejected_data_points(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  rejected_data_points_ = value;
}
inline void ExportMetricsPartialSuccess::set_rejected_data_points(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_rejected_data_points(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess.rejected_data_points)
}

// string error_message = 2;
inline void ExportMetricsPartialSuccess::clear_error_message() {
  error_message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ExportMetricsPartialSuccess::error_message() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess.error_message)
  return _internal_error_message();
}
inline void ExportMetricsPartialSuccess::set_error_message(const std::string& value) {
  _internal_set_error_message(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess.error_message)
}
inline std::string* ExportMetricsPartialSuccess::mutable_error_message() {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess.error_message)
  return _internal_mutable_error_message();
}
inline const std::string& ExportMetricsPartialSuccess::_internal_error_message() const {
  return error_message_.Get();
}
inline void ExportMetricsPartialSuccess::_internal_set_error_message(const std::string& value) {
  
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ExportMetricsPartialSuccess::set_error_message(std::string&& value) {
  
  error_message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess.error_message)
}
inline void ExportMetricsPartialSuccess::set_error_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess.error_message)
}
inline void ExportMetricsPartialSuccess::set_error_message(const char* value,
    size_t size) {
  
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess.error_message)
}
inline std::string* ExportMetricsPartialSuccess::_internal_mutable_error_message() {
  
  return error_message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ExportMetricsPartialSuccess::release_error_message() {
  // @@protoc_insertion_point(field_release:opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess.error_message)
  return error_message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ExportMetricsPartialSuccess::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    
  } else {
    
  }
  error_message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), error_message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess.error_message)
}
inline std::string* ExportMetricsPartialSuccess::unsafe_arena_release_error_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess.error_message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return error_message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ExportMetricsPartialSuccess::unsafe_arena_set_allocated_error_message(
    std::string* error_message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (error_message != nullptr) {
    
  } else {
    
  }
  error_message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      error_message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess.error_message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace metrics
}  // namespace collector
}  // namespace proto
}  // namespace opentelemetry

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_opentelemetry_2fproto_2fcollector_2fmetrics_2fv1_2fmetrics_5fservice_2eproto
