"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
from mdx.analytics.core.schema.proto import schema_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GeoLocation(google.protobuf.message.Message):
    """
    represents locations array, for geo coodinates Array[Array[lon, lat]], for cartesian coordinates Array[Array[x,y]]
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Point(google.protobuf.message.Message):
        """
        Array(x,y)
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        POINT_FIELD_NUMBER: builtins.int
        @property
        def point(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
        def __init__(
            self,
            *,
            point: collections.abc.Iterable[builtins.float] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["point", b"point"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    COORDINATES_FIELD_NUMBER: builtins.int
    type: builtins.str
    @property
    def coordinates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GeoLocation.Point]:
        """
        Array of points
        """

    def __init__(
        self,
        *,
        type: builtins.str = ...,
        coordinates: collections.abc.Iterable[global___GeoLocation.Point] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["coordinates", b"coordinates", "type", b"type"]) -> None: ...

global___GeoLocation = GeoLocation

@typing.final
class Behavior(google.protobuf.message.Message):
    """
    represent object Behavior, and comprise of attributes from object movement + [[Object]] appearance
    with highest confidence + [[Sensor]] + [[Place]]
     + [[Pose]] + [[LipActivity]] + [[Gaze]]




    the JSON representation of this object Behavior message  is stored in persistent store like Elasticsearch for search and indexing
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    LOCATIONS_FIELD_NUMBER: builtins.int
    SMOOTHLOCATIONS_FIELD_NUMBER: builtins.int
    EDGES_FIELD_NUMBER: builtins.int
    DISTANCE_FIELD_NUMBER: builtins.int
    SPEED_FIELD_NUMBER: builtins.int
    SPEEDOVERTIME_FIELD_NUMBER: builtins.int
    TIMEINTERVAL_FIELD_NUMBER: builtins.int
    BEARING_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    LENGTH_FIELD_NUMBER: builtins.int
    PLACE_FIELD_NUMBER: builtins.int
    SENSOR_FIELD_NUMBER: builtins.int
    ANALYTICSMODULE_FIELD_NUMBER: builtins.int
    OBJECT_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    VIDEOPATH_FIELD_NUMBER: builtins.int
    POSES_FIELD_NUMBER: builtins.int
    LIPACTIVITIES_FIELD_NUMBER: builtins.int
    GAZES_FIELD_NUMBER: builtins.int
    EMBEDDINGS_FIELD_NUMBER: builtins.int
    LLM_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    id: builtins.str
    """
    object id, usually a combination of sensorId + objectId
    """
    distance: builtins.float
    """
    distance traveled in meters
    """
    speed: builtins.float
    """
    avg speed in mph
    """
    timeInterval: builtins.float
    """
    timeInterval, end time - start time
    """
    bearing: builtins.float
    """
    bearing angle
    """
    direction: builtins.str
    """
    N, S, E or W based on bearing
    """
    length: builtins.int
    """
    number of raw coordinates
    """
    videoPath: builtins.str
    """
    video url if available
    """
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """
        start timestamp
        """

    @property
    def end(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """
        end timestamp
        """

    @property
    def locations(self) -> global___GeoLocation:
        """google.protobuf.Timestamp timestamp = 4;


        representing array of [lon,lat] or [x,y]
        """

    @property
    def smoothLocations(self) -> global___GeoLocation:
        """
        representing smoothened array of [lon,lat] or [x,y]
        """

    @property
    def edges(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """
        road network edges, only applicable for geo coordinates
        """

    @property
    def speedOverTime(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """
        speed over a period of the trajectory
        """

    @property
    def place(self) -> schema_pb2.Place:
        """
        where object was seen by the sensor
        """

    @property
    def sensor(self) -> schema_pb2.Sensor:
        """
        sensor details
        """

    @property
    def analyticsModule(self) -> schema_pb2.AnalyticsModule:
        """
        AnalyticsModule
        """

    @property
    def object(self) -> schema_pb2.Object:
        """
        object details, associated with this trajectory
        """

    @property
    def event(self) -> schema_pb2.Event:
        """
        event details
        """

    @property
    def poses(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[schema_pb2.Pose]:
        """
        Array of pose
        """

    @property
    def lipActivities(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[schema_pb2.LipActivity]:
        """
        Array of LipActivity
        """

    @property
    def gazes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[schema_pb2.Gaze]:
        """
        Array of Gaze
        """

    @property
    def embeddings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[schema_pb2.Embedding]:
        """
        Array of embeddings
        """

    @property
    def llm(self) -> schema_pb2.LLM:
        """
        LLM query, response, embeddings for behavior analysis and anomaly detection
        """

    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """
        addition information, that may be needed by an application
        """

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        locations: global___GeoLocation | None = ...,
        smoothLocations: global___GeoLocation | None = ...,
        edges: collections.abc.Iterable[builtins.str] | None = ...,
        distance: builtins.float = ...,
        speed: builtins.float = ...,
        speedOverTime: collections.abc.Iterable[builtins.float] | None = ...,
        timeInterval: builtins.float = ...,
        bearing: builtins.float = ...,
        direction: builtins.str = ...,
        length: builtins.int = ...,
        place: schema_pb2.Place | None = ...,
        sensor: schema_pb2.Sensor | None = ...,
        analyticsModule: schema_pb2.AnalyticsModule | None = ...,
        object: schema_pb2.Object | None = ...,
        event: schema_pb2.Event | None = ...,
        videoPath: builtins.str = ...,
        poses: collections.abc.Iterable[schema_pb2.Pose] | None = ...,
        lipActivities: collections.abc.Iterable[schema_pb2.LipActivity] | None = ...,
        gazes: collections.abc.Iterable[schema_pb2.Gaze] | None = ...,
        embeddings: collections.abc.Iterable[schema_pb2.Embedding] | None = ...,
        llm: schema_pb2.LLM | None = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["analyticsModule", b"analyticsModule", "end", b"end", "event", b"event", "llm", b"llm", "locations", b"locations", "object", b"object", "place", b"place", "sensor", b"sensor", "smoothLocations", b"smoothLocations", "timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["analyticsModule", b"analyticsModule", "bearing", b"bearing", "direction", b"direction", "distance", b"distance", "edges", b"edges", "embeddings", b"embeddings", "end", b"end", "event", b"event", "gazes", b"gazes", "id", b"id", "info", b"info", "length", b"length", "lipActivities", b"lipActivities", "llm", b"llm", "locations", b"locations", "object", b"object", "place", b"place", "poses", b"poses", "sensor", b"sensor", "smoothLocations", b"smoothLocations", "speed", b"speed", "speedOverTime", b"speedOverTime", "timeInterval", b"timeInterval", "timestamp", b"timestamp", "videoPath", b"videoPath"]) -> None: ...

global___Behavior = Behavior

@typing.final
class Incident(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InfoEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    SENSORID_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    OBJECTIDS_FIELD_NUMBER: builtins.int
    FRAMEIDS_FIELD_NUMBER: builtins.int
    PLACE_FIELD_NUMBER: builtins.int
    ANALYTICSMODULE_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    EMBEDDINGS_FIELD_NUMBER: builtins.int
    ISANOMALY_FIELD_NUMBER: builtins.int
    LLM_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    sensorId: builtins.str
    """
    sensor id
    """
    category: builtins.str
    """
    Category of the incident
    """
    isAnomaly: builtins.bool
    """
    Is the incident an anomaly
    """
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """
        start timestamp
        """

    @property
    def end(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """
        end timestamp
        """

    @property
    def objectIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """
        Array of object IDs involved in the incident. If the array is not empty, then the first ID represents the primary object.
        May be empty for incidents that don't involve any specific objects.
        """

    @property
    def frameIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """
        Array of frameIds when the incident took place (Optional)
        """

    @property
    def place(self) -> schema_pb2.Place:
        """
        where object was seen by the sensor
        """

    @property
    def analyticsModule(self) -> schema_pb2.AnalyticsModule:
        """
        AnalyticsModule: Module responsible for generating the Incident
        """

    @property
    def embeddings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[schema_pb2.Embedding]:
        """
        Embeddings can be related to object appearance or it could be representative of a scene description provided by VLM
        """

    @property
    def llm(self) -> schema_pb2.LLM:
        """
        LLM query, response, embeddings for incident analysis and anomaly detection
        """

    @property
    def info(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """
        optional attributes
        """

    def __init__(
        self,
        *,
        sensorId: builtins.str = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        objectIds: collections.abc.Iterable[builtins.str] | None = ...,
        frameIds: collections.abc.Iterable[builtins.str] | None = ...,
        place: schema_pb2.Place | None = ...,
        analyticsModule: schema_pb2.AnalyticsModule | None = ...,
        category: builtins.str = ...,
        embeddings: collections.abc.Iterable[schema_pb2.Embedding] | None = ...,
        isAnomaly: builtins.bool = ...,
        llm: schema_pb2.LLM | None = ...,
        info: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["analyticsModule", b"analyticsModule", "end", b"end", "llm", b"llm", "place", b"place", "timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["analyticsModule", b"analyticsModule", "category", b"category", "embeddings", b"embeddings", "end", b"end", "frameIds", b"frameIds", "info", b"info", "isAnomaly", b"isAnomaly", "llm", b"llm", "objectIds", b"objectIds", "place", b"place", "sensorId", b"sensorId", "timestamp", b"timestamp"]) -> None: ...

global___Incident = Incident

@typing.final
class SpaceUtilizationMetrics(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SPACEOCCUPIED_FIELD_NUMBER: builtins.int
    FREESPACE_FIELD_NUMBER: builtins.int
    TOTALSPACE_FIELD_NUMBER: builtins.int
    SPACEUTILIZATION_FIELD_NUMBER: builtins.int
    NUMEXTRAPALLETS_FIELD_NUMBER: builtins.int
    UTILIZABLEFREESPACE_FIELD_NUMBER: builtins.int
    FREESPACEQUALITY_FIELD_NUMBER: builtins.int
    ISUNSAFE_FIELD_NUMBER: builtins.int
    spaceOccupied: builtins.float
    """
    area size of the occupied space (in square meters)
    """
    freeSpace: builtins.float
    """
    area size of the free space (in square meters)
    """
    totalSpace: builtins.float
    """
    area size of the total space (in square meters)
    """
    spaceUtilization: builtins.float
    """
    the ratio/percentage that the total space is utilized/occupied
    """
    numExtraPallets: builtins.int
    """
    the max number of extra pallets that can fit into the free space
    """
    utilizableFreeSpace: builtins.float
    """
    area size of the utilizable free space
    """
    freeSpaceQuality: builtins.float
    """
    the ratio/percentage that the free space is utilizable
    """
    isUnsafe: builtins.bool
    """
    flag to indicate if the space is safe
    """
    def __init__(
        self,
        *,
        spaceOccupied: builtins.float = ...,
        freeSpace: builtins.float = ...,
        totalSpace: builtins.float = ...,
        spaceUtilization: builtins.float = ...,
        numExtraPallets: builtins.int = ...,
        utilizableFreeSpace: builtins.float = ...,
        freeSpaceQuality: builtins.float = ...,
        isUnsafe: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["freeSpace", b"freeSpace", "freeSpaceQuality", b"freeSpaceQuality", "isUnsafe", b"isUnsafe", "numExtraPallets", b"numExtraPallets", "spaceOccupied", b"spaceOccupied", "spaceUtilization", b"spaceUtilization", "totalSpace", b"totalSpace", "utilizableFreeSpace", b"utilizableFreeSpace"]) -> None: ...

global___SpaceUtilizationMetrics = SpaceUtilizationMetrics

@typing.final
class SpaceUtilizationLayouts(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FREESPACE_FIELD_NUMBER: builtins.int
    UTILIZABLEFREESPACE_FIELD_NUMBER: builtins.int
    @property
    def freeSpace(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[schema_pb2.Polygon]:
        """
        layout of the free space
        """

    @property
    def utilizableFreeSpace(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[schema_pb2.Polygon]:
        """
        layout of the utilizable free space
        """

    def __init__(
        self,
        *,
        freeSpace: collections.abc.Iterable[schema_pb2.Polygon] | None = ...,
        utilizableFreeSpace: collections.abc.Iterable[schema_pb2.Polygon] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["freeSpace", b"freeSpace", "utilizableFreeSpace", b"utilizableFreeSpace"]) -> None: ...

global___SpaceUtilizationLayouts = SpaceUtilizationLayouts

@typing.final
class SpaceUtilization(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    METRICS_FIELD_NUMBER: builtins.int
    SENSORS_FIELD_NUMBER: builtins.int
    LAYOUTS_FIELD_NUMBER: builtins.int
    id: builtins.str
    """
    ROI id
    """
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """
        timestamp in UTC format
        """

    @property
    def metrics(self) -> global___SpaceUtilizationMetrics:
        """
        Metrics regarding utilization of space
        """

    @property
    def sensors(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """
        Sensors associated with the ROI
        """

    @property
    def layouts(self) -> global___SpaceUtilizationLayouts:
        """
        Layouts of free space and utilizable free space
        """

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        metrics: global___SpaceUtilizationMetrics | None = ...,
        sensors: collections.abc.Iterable[builtins.str] | None = ...,
        layouts: global___SpaceUtilizationLayouts | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["layouts", b"layouts", "metrics", b"metrics", "timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "layouts", b"layouts", "metrics", b"metrics", "sensors", b"sensors", "timestamp", b"timestamp"]) -> None: ...

global___SpaceUtilization = SpaceUtilization
